### ISSUE TITLE
I don't have dynamic graphs

### ISSUE THREAD

**Issue by Payam-Ebadi** [scikit-multiflow/scikit-multiflow#100]
### Expected behaviour
I try to implenet a very simple example which is provided in Quick-start guide section and see the results as it is shown on the webpage.
### Actual behaviour
Instead, I have empty figure , it creates the instance for showing the plot but there is no flow inside the figure. what should I do? I need help
![Screenshot (1)_LI](https://user-images.githubusercontent.com/39265293/55477229-d092db80-5618-11e9-9c33-003f5c7bcb01.jpg)

### Steps to reproduce the behaviour

---
[*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by jacobmontiel** [comment]
Hello @Payam-Ebadi 

When using notebooks you have to set the proper matplotlib backend at the top of your notebook with the folowing line:

``` python
%matplotlib notebook
```

**Comment by Payam-Ebadi** [comment]
Dear @jacobmontiel 
Thank you so much. It worked.
