### ISSUE TITLE
[BUG] Unable to import skmultiflow.classification

### ISSUE THREAD

**Issue by ParvatYadav** [scikit-multiflow/scikit-multiflow#105]
**Describe the bug**
Unable to import skmultiflow.classification

**To Reproduce**
I installed scikit-multiflow, using the command **pip install -U scikit-multiflow**, but when I import it using **from skmultiflow.classification.lazy.knn import KNN** I get error

    ModuleNotFoundError: No module named 'skmultiflow.classification'

**Expected behavior**
There should be no error

**Comment by jacobmontiel** [comment]
Hello @ParvatYadav 

The correct import is

``` python
from skmultiflow.lazy import KNN
```

Could you tell me where you saw `from skmultiflow.classification.lazy.knn import KNN`? This seems to be from an old project structure. If you saw this in the documentation then we missed it during the cleanup.

Let me know if this helps.

**Comment by ParvatYadav** [comment]
Thanks for your reply, I followed the example given on official website, please see the link
https://scikit-multiflow.github.io/scikit-multiflow/skmultiflow.classification.lazy.knn.html

**Comment by jacobmontiel** [comment]
@ParvatYadav I see. This is a typo in the documentation.

**Comment by ParvatYadav** [comment]
@jacobmontiel  Also I think the example is old, as I am getting error while using `knn=KNN(k=8, max_window_size=2000, leaf_size=40)`

    __init__() got an unexpected keyword argument 'k'

**Comment by jacobmontiel** [comment]
@ParvatYadav I have updated the example in the code and the documentation.

Thanks for reporting this.
