### ISSUE TITLE
[FEATURE] Implementation of Streaming Half-Space-Trees (HS-Trees)

### ISSUE THREAD

**Issue by fwille** [scikit-multiflow/scikit-multiflow#109]
Recently added to MOA, I think Streaming Half-Space-Trees (HS-Trees), or one-class classifiers in general would also be a great extension to scikit-multiflow.

Link to MOA implementation: (https://github.com/Waikato/moa/blob/master/moa/src/main/java/moa/classifiers/oneclass/HSTrees.java)

Theory and the pseudocode algorithm can be reviewed in:
S. C. Tan, K. M. Ting, and T. F. Liu, “Fast anomaly detection for streaming data,” in IJCAI Proceedings-International Joint Conference on Artificial Intelligence, 2011, vol. 22, no. 1, pp. 1511–1516.:

"[...] Streaming Half-Space-Trees (HS-Trees), a fast one-class anomaly detector for evolving data streams. It requires only normal data for training and works well when anomalous data are rare. The model features an ensemble of random HS-Trees, and the tree structure is constructed without any data. This makes the method highly efficient because it requires no model restructuring when adapting to evolving data streams."

**Comment by jacobmontiel** [comment]
Thanks for the suggestion @fwille 

I have tagged it in case somebody wants to start looking into this.

**Comment by mertozer94** [comment]
Hello,

I started looking into this topic. Java implementation is pretty clear and facilitated my understanding of the paper. If no one is on this issue currently I would like to start working on it.

**Comment by jacobmontiel** [comment]
That sounds great @mertozer94 

Let me know if I can be of help.

**Comment by mertozer94** [comment]
@jacobmontiel Thanks ! I guess 'oneclass' package should be created just under the package 'skmultiflow' for the following implementations as well.

**Comment by jacobmontiel** [comment]
@mertozer94 Sorry for the delay. I had an offline discussion with other developers about this topic.

The suggestion is to create a new module ``skmultiflow.anomaly_detection`` given that one-class classifiers fall in this category (anomalies are the secondary class).

**Comment by mertozer94** [comment]
@jacobmontiel No worries. Okey, thank you for letting me know.

**Comment by mertozer94** [comment]
@jacobmontiel Sorry for being a bit late, I guess for the next times I need to set some dates. I have finished implementing and I only could have tested my code with COVERTYPE dataset because other datasets mentioned in the paper don't have a clear definition of anomalies. From my tests I realized that result depends on precise parameters settings unlike what is written on the paper. I have tried to get into the details but I couldn't find anything specific why it could be like that. I didn't have time to test with Java implementation, I will try to do it when I will have time and compare it with my parameters and update here. I have a quick question, I was using a dataset from a file, and in this project what I am seeing is usually generation of data. Do you have a suggestion of a stream generator to be also used in this feature and in the next anomaly detection modules ? I looked a bit and maybe SEA generator could be candidate. And also, the implementation assumes that attributes are normalised to [0, 1]. Should we extend the implementation to accept non normalised values?

**Comment by jacobmontiel** [comment]
Hello @mertozer94 

COVTYPE is a rather complex data set. My recommendation is to test on simpler data. Here is an anomaly generator in sine waves:

```python
from numpy import column_stack, sin, cos, arange, ones, zeros
from numpy.random import randn, rand, choice

###################################################
# GENERATE SOME DATA
###################################################
def get_synth(T=1000,n_anoms=250,contextual=False,win=4):
    ''' 
        make anomallies in sine waves 
        -----------------------------
        T = length of stream
        n_anoms = how many anomalies to insert.
    '''
    noise=0.05
    y = zeros(T)
    X = column_stack(
            [sin(arange(T)/4.)+randn(T)*noise, 
             cos(arange(T)/4.)+randn(T)*noise]
            )

    if contextual:
        contextual_anomalies = choice(T-win,n_anoms)                       # the places of trigger for a non-anomaly
        X[contextual_anomalies+win,1] = X[contextual_anomalies,0]          # the non-anomaly

    anoms = choice(T,n_anoms)                                              # the places
    X[anoms,1] = sin(choice(n_anoms)) + randn(n_anoms) * noise + 2.               # <--- 
    y[anoms] = 1.
    return X, y
```

If you decide to use a generator notice that the generators in `MOA` and `scikit-multiflow` might not provide exact matches. In this case it is better to save the data generated into a file and then load it to test both implementations.

@jread what do you think regarding
>  the implementation assumes that attributes are normalised to [0, 1]. Should we extend the implementation to accept non normalised values?

**Comment by mertozer94** [comment]
Hello @jacobmontiel 

I have realized that I have used MULCROSS data set to test the code. I also see that I didn't include AUC score, which is around 0.985 contrary to 0.998 defined in the paper. I don't know if it is normal, but I would say that the difference is coming from parameters. I could use the generator that you provided to add some tests if you don't have any other recommendation.

**Comment by jacobmontiel** [comment]
Hello @mertozer94 

Can you create a PR with your current implementation, so I can look into the code and provide feedback? This way we also move forward with the implementation review (code, documentation, testing, etc.)

**Comment by mertozer94** [comment]
Hello @jacobmontiel 

I just wanted to let you know that I created a PR request. Here is the link: https://github.com/scikit-multiflow/scikit-multiflow/pull/122

**Comment by jacobmontiel** [comment]
This feature has been completed in #122
