### ISSUE TITLE
[BUG] VFDR test fails in Python 3.6

### ISSUE THREAD

**Issue by jacobmontiel** [scikit-multiflow/scikit-multiflow#111]
**Describe the bug**
The VFDR test fails in Travis for Python 3.6 during the call to `get_measurements`

**To Reproduce**
https://github.com/scikit-multiflow/scikit-multiflow/blob/e455cb9023bda8c2a5a4ec7917c9b3c7ab8586a9/tests/rules/test_vfdr.py#L60-L65

**Expected behavior**
The test should pass on all supported versions.

**Additional context**
This bug was found during the review of #108 
The test was successfully run locally for Python 3.5, 3.6 and 3.7

**Comment by remiadon** [comment]
@jacobmontiel should this be closed ? The PR seems to be already merged

**Comment by jacobmontiel** [comment]
There seem to be some differences in the calculation of size objects for different OSes. This has been observed after upgrading the Travis configuration for macOS. Commit 74c1bed3dc4c3af15c97e723ab57708de8ee4434 includes a workaround in `test_calculate_object_size` to only asses object sizes on Linux systems. A similar approach should be applied here.
