### ISSUE TITLE
[Documentation] Add missing documentation in new rules module

### ISSUE THREAD

**Issue by jacobmontiel** [scikit-multiflow/scikit-multiflow#112]
During the review of #108 some sections of code were identified as missing a doctstring.

This issue is to add such documentation:

In the `__init__.py` file of the rules module:
```
"""
The :mod:`skmultiflow.rules` module contains ...
"""
```

Classes missing docstring:
* HellingerDistanceCriterion
* FoilGainExpandCriterion
* InfoGainExpandCriterion

**Comment by Sandy4321** [comment]
is it working now ?
HellingerDistanceCriterion FoilGainExpandCriterion InfoGainExpandCriterion
