### ISSUE TITLE
[BUG] EvaluatePrequential stops when data_points_for_classification=True and outputfile="xy.csv"

### ISSUE THREAD

**Issue by fwille** [scikit-multiflow/scikit-multiflow#116]
When using the EvaluatePrequential evaluator for plotting data points and also specifying an output file path, evaluation stops as soon as the plot shows up without an error, the plot remains empty. It works fine, when the output_file option is omitted.

**MWE:**
```
from skmultiflow.data import FileStream, WaveformGenerator
from skmultiflow.evaluation import EvaluatePrequential
from skmultiflow.trees import HoeffdingTree

# setup data stream
stream = WaveformGenerator()
stream.prepare_for_use()

# 2. Instantiate the HoeffdingTree classifier
ht = HoeffdingTree()

# evaluate prediction results
evaluator = EvaluatePrequential(show_plot=True, pretrain_size=1000, data_points_for_classification=True, max_samples=30000, output_file="test.csv")

evaluator.evaluate(stream=stream, model=[ht], model_names=['HT'])


```

**Comment by jacobmontiel** [comment]
Confirmed bug. Also relevant is that when setting `data_points_for_classification=True` and `output_file=None`, the evaluator fails to report the mean performance at the end of the evaluation. 

Thanks @fwille for reporting this. We will look into it.

**Comment by jacobmontiel** [comment]
I am uploading a fix for this issue. Additionally, I am updating the documentation to clarify the usage of this option:

```
data_points_for_classification: bool(Default: False)
        If True, the visualization used is a cloud of data points (only works for classification) and default
        performance metrics are ignored. If specific metrics are required, then they *must* be explicitly set
        using the ``metrics`` attribute.
```
