### ISSUE TITLE
[BUG] Evaluation plot captions show "Unknown metric" for precision, recall and f1

### ISSUE THREAD

**Issue by fwille** [scikit-multiflow/scikit-multiflow#126]
**Describe the bug**
Plot generated by the evaluator shows "Unknown metric" as caption for the newly added metrics precision, recall and F1 Score

**To Reproduce**

```
from skmultiflow.data import FileStream, WaveformGenerator
from skmultiflow.evaluation import EvaluatePrequential
from skmultiflow.trees import HoeffdingTree

# setup data stream
stream = WaveformGenerator()
stream.prepare_for_use()

# 2. Instantiate the HoeffdingTree classifier
ht = HoeffdingTree()

# evaluate prediction results
evaluator = EvaluatePrequential(show_plot=True, metrics=['precision', 'recall', 'f1'])

evaluator.evaluate(stream=stream, model=[ht], model_names=['HT'])
```

**Expected behavior**
Captions show name of the evaluated metric

**Screenshots**
![image](https://user-images.githubusercontent.com/17760164/62488886-ac612a00-b7c5-11e9-9ce0-4ccdbc0adcf5.png)

**Additional context**
Problem is caused by def __configure() in the evaluation_visualizer.py:
It is missing these elif blocks:
```
elif metric_id == constants.PRECISION:
    plot_tracker.sub_plot_obj.set_title('Precision')
    plot_tracker.sub_plot_obj.set_ylabel('precision')
elif metric_id == constants.RECALL:
    plot_tracker.sub_plot_obj.set_title('Recall')
    plot_tracker.sub_plot_obj.set_ylabel('recall')
elif metric_id == constants.F1_SCORE:
    plot_tracker.sub_plot_obj.set_title('F1 Score')
    plot_tracker.sub_plot_obj.set_ylabel('f1')
```

**Comment by jacobmontiel** [comment]
Thanks for reporting this @fwille 

This bug has also impact on the summary printed at the end of the evaluation. I will address both parts on the same fix.
