### ISSUE TITLE
[FEATURE] Enable memory tracking on regression tree algorithms (single-target and multi-target)

### ISSUE THREAD

**Issue by smastelini** [scikit-multiflow/scikit-multiflow#128]
The classification version of Hoeffding Tree implements mechanisms for ensuring the memory usage of the models does not exceed a chosen maximum. This action is implemented by the `enforce_tracker_limit` function and follows the ideas of [Richard Kirkb et al. (2007)](https://researchcommons.waikato.ac.nz/handle/10289/2568). The function manages inactive and active learning nodes according to the current memory usage. Next, the mentioned function is presented:

https://github.com/scikit-multiflow/scikit-multiflow/blob/e054d7fbd6c9d6c781a4dd6843329ad748880a22/src/skmultiflow/trees/hoeffding_tree.py#L1299-L1328

The regression tree algorithms invoke the `enforce_tracker_limit` in the same way as in the classification tree, but they do not implement this method. 

- Single-target regression:

https://github.com/scikit-multiflow/scikit-multiflow/blob/e054d7fbd6c9d6c781a4dd6843329ad748880a22/src/skmultiflow/trees/regression_hoeffding_tree.py#L593-L594

- Multi-target regression:

https://github.com/scikit-multiflow/scikit-multiflow/blob/e054d7fbd6c9d6c781a4dd6843329ad748880a22/src/skmultiflow/trees/multi_target_regression_hoeffding_tree.py#L821-L822

Would the solution be just removing the current implementations for regression (with the pass statement) and letting the implementation of the Classification Hoeffding Tree be used instead?

Does anyone have some opinion on that matter?

**Comment by jacobmontiel** [comment]
I don't think this is straightforward. My first concern arises from this line:

https://github.com/scikit-multiflow/scikit-multiflow/blob/e054d7fbd6c9d6c781a4dd6843329ad748880a22/src/skmultiflow/trees/hoeffding_tree.py#L1309

The promise calculation is specific for classification. What would be the proper/analogous way to do this for regression?

**Comment by smastelini** [comment]
You are right. The promise calculation takes into account the distribution of the classes in each leaf node. I thought this decision would be simpler to implement. As you mentioned, defining the likelihood of a node being split is not a straightforward decision.

I have some ideas regarding that question. Maybe some procedure considering the variance of the data in the current node could be a starting point. For example, we could reason that higher variances in a node would imply in a high potential for a split. But for sure, that is not a simple matter.

I will perform a little bit of research on this subject, and try to come with a possible solution. Any other ideas are welcome!

**Comment by jacobmontiel** [comment]
Are there any updates on this? I like the idea of using the leaf's *variance* since it is straightforward. We could also consider the count of observed samples.

**Comment by smastelini** [comment]
I recently performed some preliminary tests, and it seems that the linear correlation could be a better option.

Nevertheless, to calculate correlations incrementally, the trees would have to also monitor an additional statistic: the sum of the feature values times the target. This change is not straightforward anymore since multiple parts of the Hoeffding Tree regressor code must be changed.

Nevertheless, I intend to perform other tests using as, you mentioned, the count of observed examples, for example.
