### ISSUE TITLE
Error with show_plot=True

### ISSUE THREAD

**Issue by jmread** [scikit-multiflow/scikit-multiflow#13]
TypeError: legend() missing 1 required positional argument: 'labels'
for example, `_test_comparison_prequential.py` or `_test_file_stream.py` gives this error.

**Comment by jacobmontiel** [comment]
Should be fixed in last versions where visualization has been upgraded. 

`_test_comparison_prequential.py` no longer returns this error.

Could you confirm the name of the second file `_test_file_stream.py`?

**Comment by jmread** [comment]
An issue with matplotlib. I upgraded to matplotlib 2.2.0 and the error is no longer given.
