### ISSUE TITLE
Parameter names are not consistent in Lazy methods and Meta-algorithms

### ISSUE THREAD

**Issue by jmread** [scikit-multiflow/scikit-multiflow#14]
For example, knn uses `k` and `max_window_size` whereas sam_knn uses `n_neighbors` and `maxSize`.

**Comment by jmread** [comment]
Same goes for ensemble methods (LeveragingBagging vs AdaptiveRandomForest). We could use `base_estimator` and `n_estimators` as in sklearn for all ensemble methods.

**Comment by jacobmontiel** [comment]
Here is a proposal:

---
### Lazy methods
#### kNN and kNNAdwin
k -> n_neighbors
#### SAMkNN
knnWeights -> weighting
maxSize  -> max_window_size
LTMSizeProportion -> ltm_size
STMSizeAdaption -> stm_adaption
minSTMSize -> min_stm_size
useLTM -> use_ltm

---
### Meta learners
#### Adaptive Random Forest
nb_ensamble -> n_estimators

#### BatchIncremental, OzaBagging, OzaBaggingAdwin, LeverageBagging
h -> base_estimator
ensemble_length -> n_estimators

In `BatchIncremental`, parameter `window_size` is confusing. What is the difference with `ensemble_length`?

**Comment by jmread** [comment]
That all sounds good.
 
`window_size` involves how many instances are used for training. This is different from the number of models in the ensemble.

**Comment by jmread** [comment]
Looks like a good suggestion. 

To clarify further, the idea of `window_size` in BatchIncremental is related to the `max_window_size` in kNN, except the kNN one is updated constantly for the model prediction, whereas in BatchIncremental it is used as a snapshot to create a batch / training set. So other possibilities could be `max_window_size` to be like kNN, or `batch_size` to be faithful to the name of the classifer, but I think `window_size` is fine :-)
