### ISSUE TITLE
Adwin algorithm

### ISSUE THREAD

**Issue by enassalehali** [scikit-multiflow/scikit-multiflow#142]
Hello every one,
please i have a problem ,I added scikit-multiflow  successfully to my PC ,but when i tried to execute  the following instruction there is an error that occurred
 
"from concept_drift.adwin_buckets import AdwinRowBucketList"
the error is 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-af907bd41741> in <module>
----> 1 from concept_drift.adwin_buckets import AdwinRowBucketList

ModuleNotFoundError: No module named 'concept_drift'

**Comment by garawalid** [comment]
Hi @enassalehali 
You are not importing `scikit-multiflow` properly. See the following example of **ADWIN**:
```python
 # Imports
import numpy as np
from skmultiflow.drift_detection.adwin import ADWIN

adwin = ADWIN()

# Simulating a data stream as a normal distribution of 1's and 0's
data_stream = np.random.randint(2, size=2000)

# Changing the data concept from index 999 to 2000
 for i in range(999, 2000):
    data_stream[i] = np.random.randint(4, high=8)

# Adding stream elements to ADWIN and verifying if drift occurred
for i in range(2000):
    adwin.add_element(data_stream[i])
    if adwin.detected_change():
        print('Change detected in data: ' + str(data_stream[i]) + ' - at index: ' + str(i))
```

You can find the documentation of ADWIN [here](https://scikit-multiflow.github.io/scikit-multiflow/_autosummary/skmultiflow.drift_detection.ADWIN.html?highlight=adwin).

**Comment by enassalehali** [comment]
Hello  @garawalid
thank you for your reply 
I imported scikit-multiflow via terminal and I'm working with Jupyter , there are some problems that occurred but I solved them even the scikit-multiflow downloaded successfully.
** the above code is executed correctly without any problem, the problem with the concept_drift module.
 I tried to execute the bellow adwin code 
[adwin.zip](https://github.com/scikit-multiflow/scikit-multiflow/files/3661151/adwin.zip)

**Comment by garawalid** [comment]
@enassalehali 
I checked all the history of 'scikit-multiflow' and I couldn't find any trace of `concept_drift.adwin_buckets`. 
I think it's an external method developed outside the 'scikit-multiflow' package. 
Would you please check again the source of your code?

**Comment by enassalehali** [comment]
Hi
my source is  https://github.com/SmileYuhao/concept-drift
I can't download jacob codes (init,admin , etc ) from his repository

**Comment by jacobmontiel** [comment]
Hello @enassalehali, as Walid mentions that call is to an external method not related to our implementation. This code is from the repository that you are linking above. You need to import the method from that code, but I can not guarantee that it will work with `scikit-multiflow`.

**Comment by garawalid** [comment]
@enassalehali 
Both of them are based on the same paper, just the implementation is quite different.  
I suggest you use `scikit-multiflow` because it is easy to combine with other methods within the same package.

**Comment by jacobmontiel** [comment]
Closing this issue. No actions required.
