### ISSUE TITLE
[BUG]skmultiflow.evaluation.EvaluatePrequential

### ISSUE THREAD

**Issue by ensemblemountain** [scikit-multiflow/scikit-multiflow#147]
![image](https://user-images.githubusercontent.com/51120898/67574405-a9c5ff00-f73a-11e9-9157-57001aeb2b79.png)

I am always getting blank plot with 0 values.
Also, pretrain_size= 800 sample bot in graph title is still for 200 samples.
Please help to fix this problem

**Comment by jacobmontiel** [comment]
@ensemblemountain  Can you provide an MWE to replicate this issue?

**Comment by jacobmontiel** [comment]
Can not replicate. Closing issue.
