### ISSUE TITLE
Prequential and Holdout Evaluators refactoring

### ISSUE THREAD

**Issue by jmread** [scikit-multiflow/scikit-multiflow#15]
At the moment `task_type` in evaluate_prequential.py can be one of the following: 'classification', 'regression' or 'multi_output'. Probably, this specification is not necessary. The task type can be inferred by the evaluation metric specified (currently: `plot_options`). Furthermore, multi-output tasks can be either a regression or classification nature.

**Comment by jmread** [comment]
Good idea. I think that will work nicely.

Meanwhile a few things that come to mind:
- `j_index` (Jaccard Index) is mainly for multi-label (binary multi-output), though could conceivably be averaged across classes in the case of multi-output (there are quite many others like this, e.g., F-measure, which can be added later) but if that is not explicitly implemented, results will be a bit strange for multi-output (We can hope the user will be aware of this)
- We should be flexible wrt user-defined metrics and the values which outputs can take. For example, it is conceivable that an output `y` might be a string of text, or a graph. Other advanced metrics (e.g., Levenshtein distance apply here and can be implemented later).

**Comment by jacobmontiel** [comment]
Covered multiple aspects of the StreamEvaluator refactoring in commit 970d40a53b5ce9ebda9e19c10d7e6c9fabe99fd2

**Comment by jacobmontiel** [comment]
- [ ] Remove `task_type` fro evaluator options
- [ ] Use a DataFrame as a buffer to track performance and use it when updating the plots and saving to a file.
- [ ] Change `eval()` to `evaluate()` to avoid shadowing Python's `eval` function
