### ISSUE TITLE
[ENHANCEMENT] Add *.c files to .gitignore

### ISSUE THREAD

**Issue by smastelini** [scikit-multiflow/scikit-multiflow#153]
With the recent addition of Cython-based implementations, skmultiflow passed to create some local `*.c` files when building locally.

Currently, I have observed the files `_classification_performance_evaluator.c` and `_confusion_matrix.c` under `skmultiflow.metrics`.

It might be worth to add a new entry on the `.gitignore` to ignore them in the git change tracking.

**Comment by jacobmontiel** [comment]
Good catch. I will add those files to `.gitignore`
