### ISSUE TITLE
[BUG] Online Boosting crashes when using KNN as base learner

### ISSUE THREAD

**Issue by alirezaIzd** [scikit-multiflow/scikit-multiflow#158]
If in the first call to partial_fit in Onlineboosting with base estimator KNNADWIN I got this Error:
ValueError: KNN must be (partially) fitted on n_neighbors samples before doing any prediction.
How can I solve that?
Thanks

**Comment by fwille** [comment]
Are you sure, you are calling partial_fit() before the predict() method?

Or if you are using EvaluationPrequential, make sure pretrain_size is set to a suitable pretraining size larger than 0.

If that still doesn't help, it would be great if you could share a MWE to reproduce this.

**Comment by alirezaIzd** [comment]
Thanks for your quick respond. Yes, I'm sure , I call predict() after partial_fit() , if I use OzaBagging I don't have problem, but if use OnlineBoosting I got some Error. blow you can find my code and error:
code :
# Setting up the stream
stream = FileStream(INPUT_DATA,target_idx=-1)
stream.prepare_for_use()
X, y = stream.next_sample(200)
# clf = OnlineBoosting(base_estimator= KNNAdwin())
clf = OzaBagging(base_estimator=KNN(n_neighbors=8, max_window_size=2000, leaf_size=30), n_estimators=2)
count = 0
y_pred = []
clf = clf.partial_fit(X, y, classes=stream.target_values)
for i in np.arange(201,df.shape[0],1):
    X, y = stream.next_sample()
    clf = clf.partial_fit(X, y)
    y_pred.append(clf.predict(X))
        


Error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-847a5d7481b1> in <module>
      7 count = 0
      8 y_pred = []
----> 9 clf = clf.partial_fit(X, y, classes=stream.target_values)
     10 for i in np.arange(201,df.shape[0],1):
     11     X, y = stream.next_sample()

c:\users\aizadsh\appdata\local\_movedobjects\projects\master_thesis\sourcenv\lib\site-packages\skmultiflow\meta\online_boosting.py in partial_fit(self, X, y, classes, sample_weight)
    163                     for b in range(k):
    164                         self.ensemble[i].partial_fit([X[j]], [y[j]], classes, sample_weight)
--> 165                     if self.ensemble[i].predict([X[j]])[0] == y[j]:
    166                         self.lam_sc[i] += lam
    167                         self.epsilon[i] = self.lam_sw[i] / (self.lam_sw[i] + self.lam_sc[i])

c:\users\aizadsh\appdata\local\_movedobjects\projects\master_thesis\sourcenv\lib\site-packages\skmultiflow\lazy\knn.py in predict(self, X)
    168         """
    169         r, c = get_dimensions(X)
--> 170         proba = self.predict_proba(X)
    171         predictions = []
    172         for i in range(r):

c:\users\aizadsh\appdata\local\_movedobjects\projects\master_thesis\sourcenv\lib\site-packages\skmultiflow\lazy\knn.py in predict_proba(self, X)
    200         """
    201         if self.window is None or self.window.n_samples < self.n_neighbors:
--> 202             raise ValueError("KNN must be (partially) fitted on n_neighbors samples before doing any prediction.")
    203         proba = []
    204         r, c = get_dimensions(X)

ValueError: KNN must be (partially) fitted on n_neighbors samples before doing any prediction.

**Comment by smastelini** [comment]
Hello @alirezaIzd,

Could you provide a complete MWE to reproduce the mentioned behaviour?

**Comment by alirezaIzd** [comment]
Hello @smastelini,
Here you can finde my code:
stream = FileStream('../sea_stream.csv', target_idx=-1)
stream.prepare_for_use()
X, y = stream.next_sample(200)
clf = OnlineBoosting(base_estimator=KNN(n_neighbors=8, max_window_size=2000, leaf_size=30), n_estimators=2)
clf = clf.partial_fit(X, y, classes=stream.target_values)
clf.predict(X)

**Comment by smastelini** [comment]
Hello @alirezaIzd,

Could you also add the complete import statements? Also, I don't have access to the stream file you are using in the tests.

Maybe you can try to reproduce the error using a stream generator, e.g., [the SEA generator](https://scikit-multiflow.github.io/scikit-multiflow/_autosummary/skmultiflow.data.SEAGenerator.html).
Hence, I could run your code in my local machine to figure out what is happening.

**Comment by alirezaIzd** [comment]
Hello @smastelini :
I provide complete Code, please finde blow:


from skmultiflow.data.sea_generator import SEAGenerator
from skmultiflow.meta import OnlineBoosting
from skmultiflow.lazy import KNNAdwin,KNN
stream = SEAGenerator(classification_function = 2, random_state = 112, balance_classes = False, noise_percentage = 0.28)
stream.prepare_for_use()
X, y = stream.next_sample(200)
clf = OnlineBoosting(base_estimator=KNN(n_neighbors=8, max_window_size=2000, leaf_size=30), n_estimators=2)
clf = clf.partial_fit(X, y, classes=stream.target_values)
clf.predict(X)

**Comment by smastelini** [comment]
Hello @alirezaIzd,

Thank you for pointing out the problem.

This seems to be indeed a bug. This strange behavior happens because KNN needs to be fit on at least `n_neighbors` before making predictions.

Nonetheless, due to the boosting nature of the ensemble, the call to KNN's `partial_fit` might encompass only one sample at the time.

For example, if one set `n_neighbors=1`, the error does not happen.

Any thoughts on how to solve that @jacobmontiel?

**Comment by alirezaIzd** [comment]
@smastelini Thank you, for your support, should I wait the response of @jacobmontiel?

**Comment by jacobmontiel** [comment]
Thanks, @alirezaIzd for reporting this and @fwille and @smastelini for the additional information.

The limitation in `KNN` to require a `partial_fit` goes down to the `scikit-learn` `KDTree` structure used internally. However, we could "default" the first predictions (when the model is empty) to zeros as it is done in other algorithms.

Something like this:

```python
        if self.window is None or self.window.n_samples < self.n_neighbors:
            # The model is empty, defaulting to zero
            return np.zeros(shape=(r, len(self.classes)))
```

**Note:** The fix should be in the `predict_proba` method in `KNN`
