### ISSUE TITLE
[BUG] Evaluation of precision and recall sometimes causes "unsupported operand type(s) for -: 'int' and 'NoneType'"

### ISSUE THREAD

**Issue by fwille** [scikit-multiflow/scikit-multiflow#160]
**Describe the bug**
Bug seems not to be dependent on the used classifier and at least concerns the metrics precision and recall.

The actual error is thrown in measure_collection.py 301:
`fn = self.confusion_matrix.value_at(positive_idx, 1-positive_idx)`
which causes "unsupported operand type(s) for -: 'int' and 'NoneType'."

positive_idx is set to None by function _get_target_index() (measure_collection.py, lines 164-178) when only one target is in the targets list at this point.

**To Reproduce**
```
from skmultiflow.anomaly_detection import HalfSpaceTrees
from skmultiflow.data import SEAGenerator
from skmultiflow.evaluation import EvaluatePrequential

stream = SEAGenerator(random_state=307)
stream.prepare_for_use()


hst= HalfSpaceTrees(n_features=3, random_state=1000)

evaluator = EvaluatePrequential(show_plot=True,
                                metrics=['accuracy', 'recall'])

evaluator.evaluate(stream=stream, model=hst, model_names=['HST'])
```

**Additional context**
The problem does not occur with every input stream. I had to try out a lot of different random states to reproduce the problem with the SEAGenerator.
The Traceback printed to console actually doesn't help a lot, since the actual line which causes the error is not printed. 
The traceback is "swallowed" by the lines 365-366 in evaluate_prequential.py
```
            except BaseException as exc:
                print(exc)
```
Maybe this can be replaced by something that preserves the whole stacktrace, such as ` logging.error(exc, exc_info=True)`? This would help with debugging and  in finding the root cause of such issues.

**Comment by smastelini** [comment]
Hello again @fwille,

I performed some tests with the release `0.4.1`, and indeed the mentioned error appears.

I was able to circumvent it by changing the default behavior of the `_get_target_index` functions:

https://github.com/scikit-multiflow/scikit-multiflow/blob/4f4f7a90b01c39f98fa68141c0868079895f6eeb/src/skmultiflow/metrics/measure_collection.py#L145-L163

and

https://github.com/scikit-multiflow/scikit-multiflow/blob/4f4f7a90b01c39f98fa68141c0868079895f6eeb/src/skmultiflow/metrics/measure_collection.py#L498-L516

By changing the `add` and `add_label` defaults to `True`, the call to `_get_target_index` does not returns `None` when the requested target has not yet been seen.

Although my tests with the development version of skmultiflow did not result in errors for your MWE, I believe this strange behavior might occur in the most recent version of the framework in similar situations.

I think that changing the default values of the methods to `True` (and perhaps standardizing their parameter names, `add` x `add_label`) would be a nice solution.

What do you think @jacobmontiel?

In case the proposed solution is indeed the best one, @fwille, could you create a PR to address the issue?

**Comment by jacobmontiel** [comment]
The `_get_target_index ` method is no longer required in the improved version of the classification evaluators. There was a big overhead from it and it was prone to this kind of errors. I do not recommend creating a PR for this since the fix is in the pipeline for the next release.

**Comment by smastelini** [comment]
Nice catch @jacobmontiel!

**Comment by jacobmontiel** [comment]
If everybody agrees, then I will close this issue as it has been addressed in #150

**Comment by smastelini** [comment]
Agreed! Could we add some note or observation during the release of version 0.5.x to mention this situation?

**Comment by jacobmontiel** [comment]
> Could we add some note or observation during the release of version 0.5.x to mention this situation?

Absolutely.
