### ISSUE TITLE
[BUG] LearnNSE fails when not all the classes are observed by its batch base models

### ISSUE THREAD

**Issue by Aashi-Jindal** [scikit-multiflow/scikit-multiflow#166]
For some datasets, learn_nse.py fails. The following error shows for kdd dataset:

Traceback (most recent call last):
  File "learn_nse.py", line 62, in <module>
    preds.append(clf.predict(x)[0])
  File "/scratch/root/anaconda/anaconda3/lib/python3.7/site-packages/skmultiflow/meta/learn_nse.py", line 264, in predict
    votes = self.predict_proba(X)
  File "/scratch/root/anaconda/anaconda3/lib/python3.7/site-packages/skmultiflow/meta/learn_nse.py", line 248, in predict_proba
    return self.__vote_proba(X, len(self.ensemble), self.classes)
  File "/scratch/root/anaconda/anaconda3/lib/python3.7/site-packages/skmultiflow/meta/learn_nse.py", line 222, in __vote_proba
    votes += self.ensemble_weights[i] * y_predicts
ValueError: operands could not be broadcast together with shapes (1,23) (1,2) (1,23)

The snippet of the code is as follows:

```python
    import numpy as np
    from skmultiflow.meta import LearnNSE

        clf = LearnNSE(n_estimators=n_estimators, window_size=max_window_size)
        clf.partial_fit(data[0].reshape(1,data.shape[1]), [label[0]], classes=np.unique(label))

        preds = []
        for i in range(data.shape[0]):
            if (i+1)%int((len(label)/20)) == 0:
                print('%d%%' % int(np.round((i+1.)/len(label)*100, 0)))
            x = data[i].reshape(1, data.shape[1])
            y = np.array([int(label[i])])
            preds.append(clf.predict(x)[0])
            clf.partial_fit(x, y)

```
The kdd dataset has been downloaded from https://github.com/vlosing/driftDatasets, where labels have been mapped to integer values. The map of labels is as follows:
normal:0
buffer_overflow:1
loadmodule:2
perl:3
neptune:4
smurf:5
guess_passwd:6
pod:7
teardrop:8
portsweep:9
ipsweep:10
land:11
ftp_write:12
back:13
imap:14
satan:15
phf:16
nmap:17
multihop:18
warezmaster:19
warezclient:20
spy:21
rootkit:22

**Comment by smastelini** [comment]
Hello @Aashi-Jindal, thanks for pointing out that. Could you provide a complete MWE for this problem?

Thus, we can better track possible roots for the problem.

**Comment by Aashi-Jindal** [comment]
Please find below mwe:
```python
import numpy as np
import logging
import sys
import os
from skmultiflow.meta import LearnNSE


if __name__ == '__main__':

    logging.basicConfig(format='%(message)s', level=logging.INFO)
    #Read data and labels
    dataN = sys.argv[2]
    dataPath = os.path.join('driftDatasets-master', sys.argv[1], dataN)
    datafile = os.path.join(dataPath, sys.argv[3])
    logging.info(datafile)
    labelfile = os.path.join(dataPath, sys.argv[4])

    data = np.genfromtxt(datafile, delimiter=sys.argv[5])
    logging.info(f'{data.shape[0]} samples')
    logging.info(f'{data.shape[1]} dimensions')
    label = np.genfromtxt(labelfile, dtype=np.int)
    ######################################################################

    #choose no. of estimators
    n_estimators = 15

    max_window_size = min(5000, np.floor(0.10*len(label)))

    clf = LearnNSE(n_estimators=n_estimators, window_size=max_window_size)
    clf.partial_fit(data[0].reshape(1,data.shape[1]), [label[0]], classes=np.unique(label))

    logging.info('applying model on dataset')
    for i in range(data.shape[0]):
        if (i+1)%int((len(label)/20)) == 0:
            logging.info('%d%%' % int(np.round((i+1.)/len(label)*100, 0)))
        x = data[i].reshape(1, data.shape[1])
        y = np.array([int(label[i])])
        pred_ = clf.predict(x)[0]
        clf.partial_fit(x, y)
```
The kdd dataset along with its labels is available on https://drive.google.com/drive/folders/1J8izTUEfEpl6cZHkjXTvIDreFC61dr2h?usp=sharing

**Comment by smastelini** [comment]
Hello @Aashi-Jindal,

Thanks for the example. However, I couldn't open the label file. It seems to be empty.

Besides, could you also include the call signature for your code? There are some needed parameters to pass to the script (with `sys.argv`).

**Comment by Aashi-Jindal** [comment]
The call signaure is:
gunzip KDDCup99_fullRemap.data.gz
gunzip KDDCup99_fullRemap.labels.gz
python learn_nse_mwe.py

I have checked again on drive. The labels file seems to be fine.
I have also edited the previous comment where I had shared mwe.

**Comment by smastelini** [comment]
Hello @Aashi-Jindal,

I was able to both access the data and run your MWE. I did tests in the development version of  `skmultiflow` and also in version `0.4.1`.

Nonetheless, your code ran without errors.

Which version of `skmultiflow` are you using?

**Comment by smastelini** [comment]
Thanks @Aashi-Jindal. I was able to reproduce the error.

I don't think the problem is specifically related to your dataset. Instead, by performing some tests and research, I found that the problem relates to the way `predict_proba` is calculated.

When using a batch incremental approach (as default), the batch classifiers just output the probabilities for the classes they have seen so far.

**Comment by jacobmontiel** [comment]
The solution seems good to me:

```python
def predict_proba_ordered(probs, classes_, all_classes):
    """
    probs: list of probabilities, output of predict_proba 
    classes_: clf.classes_
    all_classes: all possible classes (superset of classes_)
    """
    proba_ordered = np.zeros((probs.shape[0], all_classes.size),  dtype=np.float)
    sorter = np.argsort(all_classes) # http://stackoverflow.com/a/32191125/395857
    idx = sorter[np.searchsorted(all_classes, classes_, sorter=sorter)]
    proba_ordered[:, idx] = probs
    return proba_ordered
```

The key here is to make sure that it really keeps the order of the classes. Also important is to consider the overhead from the sorting operation given that we will be performing it for each instance.
