### ISSUE TITLE
[BUG] Automatic build fails with new scikit-learn version (v0.22)

### ISSUE THREAD

**Issue by smastelini** [scikit-multiflow/scikit-multiflow#173]
**Describe the bug**

The recently updated version of sklearn (v0.22) seems to break some of the automatic tests for skmultiflow. The tests relate, for instance, with `k-NN` models. The sklearn [changelog](https://scikit-learn.org/stable/whats_new/v0.22.html) shows that multiple algorithms were affected by the update.

We might have to update some automatic tests to address the changes. Nevertheless, this fact should be investigated with caution.

**Comment by jacobmontiel** [comment]
A temporary workaround is available in 2bf6f67918515e1e1fa1c51b4dac8befd625bba2

This commit defines a range of versions of `scikit-learn` (`>=0.20,<0.22`) in the requirements. We are skipping `0.22.0` temporarily in order to investigate and perform any change(s) on our side.
