### ISSUE TITLE
[FEATURE] Getting the traces from evaluation

### ISSUE THREAD

**Issue by bangxiangyong** [scikit-multiflow/scikit-multiflow#174]
How can I get the traces from the evaluation metrics? Say for example, after running the evaluation, I want to get the list of "mean" and "current" accuracy scores which are plotted on the graphs.

```

from skmultiflow.data import WaveformGenerator
from skmultiflow.trees import HoeffdingTree
from skmultiflow.evaluation import EvaluatePrequential

stream = WaveformGenerator()
stream.prepare_for_use()

ht = HoeffdingTree()

evaluator = EvaluatePrequential(show_plot=True,
                                pretrain_size=200,
                                max_samples=20000)

evaluator.evaluate(stream=stream, model=ht)


```

**Comment by jacobmontiel** [comment]
You can save the evaluation results to a csv file. You can do so by setting the `output_file` option of the `EvaluatePrequential`class ([link to doc](https://scikit-multiflow.github.io/scikit-multiflow/_autosummary/skmultiflow.evaluation.EvaluatePrequential.html#skmultiflow.evaluation.EvaluatePrequential))
