### ISSUE TITLE
[BUG] HAT not building alternate trees

### ISSUE THREAD

**Issue by fwille** [scikit-multiflow/scikit-multiflow#180]
**Describe the bug**
I updated to the new dev version and compared perfomance of the HAT classifier with the MOA implementation and noticed, that scikit-multiflows HAT is not building any alternate trees on my data that contains multiple concept drifts. Below I plotted the Tree depths of HAT and HT in MOA and scikit-multiflow, tested on the same dataset. 

HAT / HT Tree Depth in MOA:
![UNSW_drift_weka3](https://user-images.githubusercontent.com/17760164/71000200-2a6dff80-20db-11ea-936e-19d64d1af4bd.png)

HAT / HT Tree Depth in scikit-multiflow:
![sk_HAT_HT_depth](https://user-images.githubusercontent.com/17760164/71004570-5ccf2b00-20e2-11ea-9246-7f1854d94a69.png)

The difference between HAT and HT is only caused by the bootstrap_sampling of HAT, if I disable it, the tree structure is identical between HAT and HT.

From what I observed so far, error.change in ada_split_node.py never evaluates to True:
https://github.com/scikit-multiflow/scikit-multiflow/blob/f33717b0807747651a2292f0645c7b78efe55dbc/src/skmultiflow/trees/nodes/ada_split_node.py#L85-L88

I am not sure, if the root cause for the lack of alternate trees being built lies in HAT or ADWIN implementation.

**To Reproduce**
I compared the performance between MOA and skmultiflow using a custom dataset with artificial drifts created by sorting by a feature that is strongly correlated with the label. I am still working on a MWE that uses ConceptDriftStream, but I am not sure about the configurations I should use in order to detect situations where ADWIN should detect a concept change. 

Although I tested some configurations with the ConceptDriftStream, I never was able to create an example where the HAT trains at least one alternate tree.

I am not sure, if the Stream Generators in MOA and scikit-multiflow are comparable for this matter.
Any suggestions on this are welcome!

**Additional context**
Additionally, the docstring in adwin.py does not match the behavior in the ada_split_node.py, one of these mixes up the interepretation of 0 and 1. However, this is not the cause of the problem described above, since changing this does not cause alternate trees being built.

https://github.com/scikit-multiflow/scikit-multiflow/blob/f33717b0807747651a2292f0645c7b78efe55dbc/src/skmultiflow/drift_detection/adwin.py#L180-L184

https://github.com/scikit-multiflow/scikit-multiflow/blob/f33717b0807747651a2292f0645c7b78efe55dbc/src/skmultiflow/trees/nodes/ada_split_node.py#L68

https://github.com/scikit-multiflow/scikit-multiflow/blob/f33717b0807747651a2292f0645c7b78efe55dbc/src/skmultiflow/trees/nodes/ada_split_node.py#L75-L78

**Comment by smastelini** [comment]
Thank you @fwille for pointing that out.

Were the settings used for both MOA's and skmultiflow implementations of HAT the same during your tests?

**Comment by fwille** [comment]
The only parameter I used for the test in skmultiflow is nominal_attributes. To achieve the same effect in MOA, I marked the same columns as categorical in the arff file I used as input. 

Apart from that, I used default settings for both, which as far as I can tell are identical.
