### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by jmread** [scikit-multiflow/scikit-multiflow#19]
This uninformative error comes from `LeveragingBagging`, under for example, `covtype.csv`. See `_test_file_stream_multiple_cfier.py` ;the error is quite subtle, in fact it is not even explicitly an error:
```
root - INFO - Prequential Evaluation
root - INFO - Generating 7 targets.
root - INFO - Pre-training on 100 samples.
root - INFO - Evaluating...
'NoneType' object is not iterable
root - INFO - Evaluation time: 0.000 s
root - INFO - Total instances: 100
root - INFO - Global performance:
root - INFO - Learner 0 - Accuracy     : 0.000
```

**Comment by jacobmontiel** [comment]
The root cause seems to be in the `KNN` (used as default model in leveraging bag) when working with multi-label data.

**Comment by jmread** [comment]
Good, that can probably be fixed. The thing is that sometimes the problems are very silent, .. and its difficult to see the problem. There is another one: 
"classes should include all valid labels that can be in y"
which probably comes from sklearn -- maybe we should break the stream and return an error when these things happen, rather than continuing and producing a summary at the end as if all was well?
