### ISSUE TITLE
Inconsistent use of sample_weight vs weight parameters [BUG]

### ISSUE THREAD

**Issue by benman1** [scikit-multiflow/scikit-multiflow#190]
Estimators use as a parameter either **weight** or **sample_weight** in the partial_fit() method. This gives an inconsistent API across estimators. In sklearn, it is always **sample_weight**. I think this is the convention, scikit-multiflow should follow. I can fix this, if there are no objections.

Thanks!

**Comment by jacobmontiel** [comment]
Hello @benman1 

Thanks for identifying this. Could you provide an example where this inconsistency is present? Indeed this should be the same (`sample_weight`) across all estimators.

**Comment by benman1** [comment]
Hi, Jacob

Thanks for responding. I've just looked back at this and only found two instances were this was inconsistent (for some reason, I thought there were more). I've created a PR that fixes this: [PR](https://github.com/scikit-multiflow/scikit-multiflow/pull/202).

Thanks!
Ben.
