### ISSUE TITLE
[FEATURE] memory metrics

### ISSUE THREAD

**Issue by Miso-K** [scikit-multiflow/scikit-multiflow#206]
I am working on new ensemble model but I would like to compare its performance against other models. It is somehow possible to get memory consumption metrics per model when evaluate models ?
It could be just text info like running_time is.

**Comment by jacobmontiel** [comment]
Yes, there is.

If you are using an `Evaluator` you just need to include `model_size` in the list passed to the `metrics` option. 

Otherwise, you can use the following method:

```python
from skmultiflow.utils import calculate_object_size
```

**Comment by Miso-K** [comment]
Thank you, it is working.
But I can't find info about output value. It is averaged size or computed in each period ?

**Comment by jacobmontiel** [comment]
In the evaluator, it is the current model size measured every `n_wait` samples.
