### ISSUE TITLE
test for drift detection, how can calculate the expected indices?

### ISSUE THREAD

**Issue by jzxywpf** [scikit-multiflow/scikit-multiflow#210]
In the test file, the DDM method for concept drift detection, I saw the expected_indices is [103,1060], how can you calculate it? Cheers, Pingfan

**Comment by jacobmontiel** [comment]
Hi @jzxywpf ,

The index is not calculated. On each new sample, `DDM` checks the error rate. If the error increases over a threshold then `DDM` raises a flag that indicates that there is a change. For more information:

https://scikit-multiflow.github.io/scikit-multiflow/_autosummary/skmultiflow.drift_detection.DDM.html?highlight=ddm#skmultiflow.drift_detection.DDM

And the original paper:
> João Gama, Pedro Medas, Gladys Castillo, Pedro Pereira Rodrigues: Learning with Drift Detection. SBIA 2004: 286-295

**Comment by jacobmontiel** [comment]
Closing without action required.

**Comment by jzxywpf** [comment]
> Hi @jzxywpf ,
> 
> The index is not calculated. On each new sample, `DDM` checks the error rate. If the error increases over a threshold then `DDM` raises a flag that indicates that there is a change. For more information:
> 
> https://scikit-multiflow.github.io/scikit-multiflow/_autosummary/skmultiflow.drift_detection.DDM.html?highlight=ddm#skmultiflow.drift_detection.DDM
> 
> And the original paper:
> 
> > João Gama, Pedro Medas, Gladys Castillo, Pedro Pereira Rodrigues: Learning with Drift Detection. SBIA 2004: 286-295

Hi Jacob:

Thanks for your reply, there is another thing I still can not figure out. DDM for concept drift detection
![image](https://user-images.githubusercontent.com/24716335/74986013-9f89e800-5430-11ea-8ade-0128cbb67c8e.png)
there are warning detect method and change detection method, but they just use the method in base class, however, there is just a declaration in the base class 
![image](https://user-images.githubusercontent.com/24716335/74986166-eaa3fb00-5430-11ea-9e47-3645911aeeae.png)
I have read the paper about it, there should have a base learner to learn some sample then predict, but I can not find it, could you give some tips? I may overlook something.

Best,

Pingfan

**Comment by jacobmontiel** [comment]
Hello @jzxywpf 

The `detected_warning_zone` method is just to query the internal variable which is actually updated inside `add_element`. In other words, as a new sample is observed, the drift detector updates its internal state and potentially raises a warning or detection flag. Notice that not all drift detectors raise a warning flag.

The base learner from the paper is just the method to pair with the drift detector. Drift detectors are (in most cases) used to track the performance of an estimator (the base learner).

The example in the documentation uses synthetically generated data. Here is an example with a base learner:

```python
from skmultiflow.bayes import NaiveBayes
from skmultiflow.drift_detection import ADWIN
from skmultiflow.data import ConceptDriftStream

stream = ConceptDriftStream(position=1000, width=100, random_state=1)
estimator = NaiveBayes()
drift_detector = ADWIN()

max_samples = 2000
cnt = 0

while stream.has_more_samples() and cnt < max_samples:
    X, y = stream.next_sample()
    y_pred = estimator.predict(X)
    drift_detector.add_element(int(y_pred[0] == y[0]))
    if drift_detector.detected_change():
        print("Drift detected at {}".format(cnt))
        drift_detector.reset()
    estimator.partial_fit(X, y)
    cnt += 1
```

**Note:** Drift detectors may have different expectations regarding the input data, in this case, ADWIN expects correct classifications encoded as 1
