### ISSUE TITLE
[DOC] Support versioning of documentation

### ISSUE THREAD

**Issue by jacobmontiel** [scikit-multiflow/scikit-multiflow#212]
As the code base grows and fixes/updates are integrated we need a clear way of showing the differences between the release version and the latest code. Documentation versioning is not supported in `ghpages`. `readthedocs`(https://readthedocs.org/) seems like the natural option since it would require minimum changes on our side given its support for `Sphinx` and the fact that we are using the `sphinx_rtd_theme` theme.

**Comment by smastelini** [comment]
The documentation versioning is of increasingly importance given the constant addition of novel algorithms, as well as the recent changes in the naming convention. @jacobmontiel, is your idea to make the links in skmultiflow's webpage point to `readthedocs`?

**Comment by jacobmontiel** [comment]
Exactly @smastelini, the front page would remain https://scikit-multiflow.github.io/ 

On the other hand, the documentation would be hosted in `readthedocs`. We would just need to update the current links to point to the new address.

Another important element of `readthedocs` is that the documentation creation/update process is automatic. This ensures that the `latest` version would reflect the latest changes in the code. Currently, the documentation is manually updated only for a release.
