### ISSUE TITLE
[CICD] Migrate from Travis to Azure Pipelines

### ISSUE THREAD

**Issue by jacobmontiel** [scikit-multiflow/scikit-multiflow#213]
Currently, we are using `Travis` as our CI/CD tool. This issue is to discuss migrating to `Azure Pipelines`.

Comments:
* Azure Pipelines are used in our `conda-forge` [`scikit-multiflow-feedstock`](https://github.com/conda-forge/scikit-multiflow-feedstock) to create artifacts for multiple environments.
  * Potentially we can use Azure Pipelines to deploy artifacts to `PyPI`
  * Note: Is this possible in Travis?
* Azure Pipelines provides unlimited CI/CD minutes and 10 parallel jobs to every open source project for free.

**Comment by smastelini** [comment]
Big players in the data mining (and related areas) are currently using this solution. `pandas` is an example.

**Comment by garawalid** [comment]
It's possible to use Travis CI to publish an artifact to pypi.We just install twine and use it.

I have some concerns about the published version.

The pypi repository don't allow to overwrite the same version. So if you want to make it automatically what's the rule to publish an artifact? Is it with each commit in the master? Also, how you are willing to handle the versioning ?

I think it's better to keep the release manually. I saw many open source projects follow this approach.

**Comment by jacobmontiel** [comment]
@garawalid those are valid concerns. Indeed, the indexer does not allow overwriting/updating versions (learned the hard way) which makes sense. I was thinking that our trigger should be the 
creation of a new tag, i.e. as new releases are tagged.

In our case, additional steps are required for `PyPI` since we upload the ["`manylinux`"](https://github.com/pypa/manylinux) binaries. This seems promising for this purpose: https://github.com/scikit-hep/azure-wheel-helpers

I am in favor of a hybrid approach. Either we could trigger a pipeline based on a new tag or we manually trigger a "release" pipeline. The goal is to automate the generation of artifacts in order to streamline the release process.

**Comment by garawalid** [comment]
@jacobmontiel 
I find that pushing a tag to trigger the pipeline is a good strategy. I absolutely agree with you, releasing should be smooth and automatically!

I never used Azure pipeline before, but it sounds promising!  

Please let me know if you need some help here!

**Comment by jacobmontiel** [comment]
A simple pipeline with similar behaviour to what we have in Travis:

https://dev.azure.com/scikit-multiflow/scikit-multiflow/_build/results?buildId=18&view=results

Matrix:
- OS: Linux, macOS, Windows
- Architecture: x64
- Runs tests on Python 3.5-3.8 for Linux
- Runs tests on Python 3.7-38 for macOS and Windows

---

I have been thinking about the release/packaging task. There is also the option to use [`GitHub Actions`](https://github.com/scikit-multiflow/scikit-multiflow/actions/new). Here is an example: [`Publish Python Package
`](https://github.com/actions/starter-workflows/blob/master/ci/python-publish.yml)

**Comment by garawalid** [comment]
@jacobmontiel
The example is clear and simple.

I don't see any difference between Github Actions and Azure Pipeline, they are quite the same. I think it will be easier to maintain if we have only one pipeline that lunch tests for each platform, then if there is a tag in the commit such as `v1.0.2` it creates a release and publishes it.  
It's possible to trigger some tasks based on a tag in both Github Actions and Azure Pipeline.

What do you think ?

**Comment by garawalid** [comment]
Also what about adding a PEP8 style checker in the pipeline like `flake8`. We probably need to fix some PEP8 rules and lint the whole project with one commit (To keep the history clear)

It will make the reviewing quite faster since it's required in each pull request and the reviewer should verify it.

**Comment by jacobmontiel** [comment]
> I think it will be easier to maintain if we have only one pipeline that lunch tests for each platform, then if there is a tag in the commit such as `v1.0.2` it creates a release and publishes it.
> It's possible to trigger some tasks based on a tag in both Github Actions and Azure Pipeline.
> 
> What do you think ?

I agree that it is better to keep things simple. This seems like a promising solution: 

https://iscinumpy.gitlab.io/post/azure-devops-releases/

Basically have a pipeline for releases, in our case, we would trigger it manually and will only be used to generate wheel files for PyPI.

**Comment by jacobmontiel** [comment]
> Also what about adding a PEP8 style checker in the pipeline like `flake8`. We probably need to fix some PEP8 rules and lint the whole project with one commit (To keep the history clear)
> 
> It will make the reviewing quite faster since it's required in each pull request and the reviewer should verify it.

This is definitely worth investing in. We can create new issues: one for the "release" pipeline and one to add support for `flake8`.

Comments?

**Comment by garawalid** [comment]
> > Also what about adding a PEP8 style checker in the pipeline like `flake8`. We probably need to fix some PEP8 rules and lint the whole project with one commit (To keep the history clear)
> > It will make the reviewing quite faster since it's required in each pull request and the reviewer should verify it.
> 
> This is definitely worth investing in. We can create new issues: one for the "release" pipeline and one to add support for `flake8`.
> 
> Comments?

Sounds good for two different pipelines. I'll open an issue for the linting part. I'll work on it.  
Also, I'll be happy to review the `release` pipeline.
