### ISSUE TITLE
Automate get_info() method in base abstract object 

### ISSUE THREAD

**Issue by jacobmontiel** [scikit-multiflow/scikit-multiflow#22]
### Expected behaviour
`get_info()` should be automatically generated.
See: https://docs.python.org/3/library/inspect.html

### Actual behaviour
Currently, `get_info()` is an abstract method that needs to be implemented manually across `scikit-multiflow`

**Comment by gilbertoolimpio** [comment]
@jacobmontiel 

Could you explain a little better how I should work on this issue?

I would like to help in this too!

Tks in advance!

**Comment by jacobmontiel** [comment]
The goal is to make it a function in the base object so all extended classes will inherit it.

This somehow related to #45. The base class in `scikit-learn` provides this type of functionality [here](https://github.com/scikit-learn/scikit-learn/blob/bac89c253b35a8f1a3827389fbee0f5bebcbc985/sklearn/base.py#L166).

I am not fully convinced about making `scikit-multiflow` objects extensions of `scikit-learn`'s `BaseEstimator`, but implementing simiar `get_params` and `set_params` woould get us closer.
