### ISSUE TITLE
[BUG] Error: IndexError: list index out of range in Half Space Trees example

### ISSUE THREAD

**Issue by dennaloh** [scikit-multiflow/scikit-multiflow#225]
Hi I keep getting the following error upon running the test example. I've also attempted to change the values of the parameters but to no avail. 

`  File "/Users/dennaloh/anaconda3/lib/python3.7/site-packages/skmultiflow/anomaly_detection/half_space_trees.py", line 163, in predict
    y_proba = self.predict_proba(X)
  
File "/Users/dennaloh/anaconda3/lib/python3.7/site-packages/skmultiflow/anomaly_detection/half_space_trees.py", line 197, in predict_proba
    y_proba = self.ensemble[i].predict_proba(X, max_score)

IndexError: list index out of range`

**Comment by smastelini** [comment]
Hi @dennaloh, thank you for reporting that. Could you provide a MWE so that we could reproduce this unexpected behavior?

**Comment by jacobmontiel** [comment]
Closing due to lack of response. No action required.
