### ISSUE TITLE
Add more stream generators

### ISSUE THREAD

**Issue by jacobmontiel** [scikit-multiflow/scikit-multiflow#24]
We want to increase the number of available stream generators:
- [x] Agrawal
- [x] HyperPlane
- [x] LED
- [x] LED + drift
- [x] Mixed
- [x] Sine
- [x] STAGGER
- [x] Dataset to stream

Nice to have:
API support for external services (e.g Twitter, AWS, TensorFlow)

**Comment by jacobmontiel** [comment]
About the `Dataset to stream` generator:

We want the user to have a way to convert their own data (X, Y) into a stream object to be used inside `scikit-multiflow`

The implementation should be similar to `FileStream`

Input:
- np.array [X, Y]
- Pandas DataFrame

We need to account for cases where the user passes:
Multi-label [X, Y]: classification or regression
Single label [X, y]: classification or regression

**Comment by jacobmontiel** [comment]
For the `Dataset to stream` generator, we could receive a single matrix D=[X, Y] or receive them separately.

1) `DataStream(data=D, target_idx=-1, n_targets=1, cat_features_idx=None)`
2) `DataStream(X=X, Y=Y, cat_features_idx=None)`

**Option 1** is similar to `FileStream` and the user needs to make the explicit declaration of how the data should be split. Additionally, if the data is already in X, Y format then the user has to concatenate it.

**Option 2** follows the learner signature (X, y). In this case, the user is in charge of splitting data. `n_targets` is inferred from `y.shape`.

Comments @jmread ?

**Comment by jmread** [comment]
I would be in favour of Option 2.  Assuming that it is not easy to be flexible and include *both* options, i.e., the possibility to specify Y *or* target_index, n_targets=1.

**Comment by jacobmontiel** [comment]
I think supporting both options is feasible, is it necessary though?

@Darkmyter  @krifiMedAmine  please confirm that current implementation uses **Option 1** and that we can support both modes. 

We also need to account for the case where the user passes `Y` and `target_index`

**Comment by jmread** [comment]
It sounds like that would work well as a solution to support both options.

**Comment by Darkmyter** [comment]
We updated the DataStream Generator, now it takes as parameters a single Dataset or X and Y separately.

**Comment by jacobmontiel** [comment]
Some comments:

1. In the init method
```python
 def __init__(self, data=None, y=None, target_idx=-1, n_targets=1, cat_features_idx=None):
```
`data` should not have a default value in orer to force the user to set it.

2. Purpose of the internal variable `_flag` is not clear from the name.

3. Avoid if -- elif when they lead to the same code, for example
```python
if not self._flag:
    self._y = y
elif isinstance(y, np.ndarray) or isinstance(y, pd.DataFrame):
    self._y = y
```
Can be rewritten as
```python
if self._flag or (isinstance(y, np.ndarray) or isinstance(y, pd.DataFrame)):
    self._y = y
```
Same applies for:
```python
if isinstance(X, np.ndarray) or isinstance(X, pd.DataFrame):
    self._X = X
elif not self._flag:
    self._X = X
```

**Comment by jacobmontiel** [comment]
@krifiMedAmine  @Darkmyter  Seems that we are ready to close this issue. Please confirm.

**Comment by krifiMedAmine** [comment]
Everything works in the stream generators , we changed what was needed to be changed and run the tests so yes this issue should be closed
