### ISSUE TITLE
Hyperparameter Tuning

### ISSUE THREAD

**Issue by jmrichardson** [scikit-multiflow/scikit-multiflow#242]
Hi, I am new to this project and was wondering if anyone could help me with how to tune hyper parameters?  Perhaps something like gridsearch or other auto tuning method example?  

Thanks for any help

**Comment by jacobmontiel** [comment]
Hi @jmrichardson 

Currently, there are no built-in methods available for this. You could try some external tools such as [ParameterGrid](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.ParameterGrid.html) to create the hyper-parameter configurations to loop over.

**Comment by jmrichardson** [comment]
Thanks,  will have a look.
