### ISSUE TITLE
Keep File Stream Open

### ISSUE THREAD

**Issue by jmrichardson** [scikit-multiflow/scikit-multiflow#243]
I have setup a file stream, performed an evaluation, then added 5 more samples to the data file.  However, the stream says there are no more remaining samples.  Am I incorrect to assume that when you add samples to the data file stream, it will identify the new samples as available to the stream?  Here is my code:

```
from skmultiflow.evaluation import EvaluatePrequential
from skmultiflow.data.file_stream import FileStream
from skmultiflow.trees import HoeffdingTree
from skmultiflow.data import AGRAWALGenerator
import pandas as pd
import numpy as np

gen = AGRAWALGenerator()
gen.prepare_for_use()

X, y = gen.next_sample(1000)
df = pd.DataFrame(np.hstack((X,np.array([y]).T)))
df = df.astype({9: int})
df.to_csv("data.csv", index=False)

stream = FileStream('data.csv')
stream.prepare_for_use()

model = HoeffdingTree()
evaluator = EvaluatePrequential(show_plot=False, pretrain_size=200, restart_stream=False)
evaluator.evaluate(stream=stream, model=model)

X, y = gen.next_sample(5)
df = pd.DataFrame(np.hstack((X,np.array([y]).T)))
df = df.astype({9: int})
df.to_csv('data.csv', mode='a', header=False, index=False)

stream.n_remaining_samples()
stream.has_more_samples()


```

**Comment by jacobmontiel** [comment]
That is incorrect. The `FileStream` class only reads the file once. In other words, the `FileStream` object is not aware of any changes to the file after its creation.

If you need to read from a dynamic source then you can wrap the code for reading the data source inside an instance of the `Stream` class.

**Comment by jmrichardson** [comment]
Thank you for the response!  I believe I saw reference to [Streamz ](https://github.com/python-streamz/streamz)integration?  Would this be a recommended approach as well?  I am thinking of using it for other needs and may serve well here.  Thanks.

**Comment by jacobmontiel** [comment]
I believe is an interesting option. Unfortunately, we haven't been able to move forward in that direction but for the case that you mention seems to be a good fit.
