### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by hitz9** [scikit-multiflow/scikit-multiflow#246]
Hi, I want to detect drift in my own dataset and I have an error in stream_prepare_for_use()

![](https://i.gyazo.com/336b01eb25f4898507685ba0a045f34c.png)

![](https://i.gyazo.com/0f49107fa6a430fb5936ebba3f2e50b1.png)
)
![](https://gyazo.com/b7a13f5e6e93302c6097f7edd50a3995.png)

![](https://i.gyazo.com/707be47459c2e10ad0aff72573522dd2.png

**Comment by hitz9** [comment]
Whats happening?

**Comment by smastelini** [comment]
Hi @hitz9, my best guess (without a MWE) is that the `;` at the end of each line are making `FileStream` identify the single feature in your data as the type `object`.

This comes from the inner `pandas` utilization in the stream handler. My suggestion is to drop the semicolon of your data.

**Comment by jacobmontiel** [comment]
Closing this issue because there has been further information from the original author. No action is required.
