### ISSUE TITLE
Add predict_proba to Hoeffding Tree

### ISSUE THREAD

**Issue by jacobmontiel** [scikit-multiflow/scikit-multiflow#26]
### Expected behaviour
`predict_proba` shall return an array with the probability for each class.

Example: For a binary classification problem, the corresponding leaf node contains `{0:5, 1:10}`

Step 1. Normalize the dictionary
`{0:5, 1:10}` --> `{0:1/3, 1:2/3}`

Step 2: Convert the dictionary to an array where the index corresponds to the class:
`{0:5, 1:10}` --> `[1/3, 2/3]`

**Warning:** We need to account for cases where there are missing classes (array indices) in the dictionary:
`{0:5, 2:10}` --> `[1/3, 0, 2/3]`

Additionally, we need to consider the generic approach to be used across `scikit-multiflow`. Suggestion:
```python
import operator
def predict(X):
   ...
   y_proba = self.predict_proba(X)`
   # Get index (class) for higest probability   
   index, _ = max(enumerate(y_proba), key=operator.itemgetter(1))   
   return index
```

### Actual behaviour
Not implemented yet

**Comment by jacobmontiel** [comment]
Related to #21

**Comment by Darkmyter** [comment]
What about the case when the missing classes are higher than the ones present: 
``{0:5, 1:3}``, if we consider that class 2 exists should we add it to the array --> ``[5/8, 3/8, 0]`` or not ?

**Comment by Darkmyter** [comment]
Added ``predict_proba`` to ``Hoeffding_tree.py``.
commit id: 1ab0adcb79fa05f8fbe29a76cece193a2d5e1113

**Comment by jacobmontiel** [comment]
>  if we consider that class 2 exists should we add it to the array --> [5/8, 3/8, 0] or not ?

Yes, `predict_proba` should return an array with probability for each target (`stream.target_values`). The size of the array shall match `stream.n_targets`

@Darkmyter What do you mean by:

> Python 3.6 output is different from 3.4 and 3.5

@jmread Could you confirm if this solves #21?

**Comment by jmread** [comment]
At the moment it is not fixed, at least according to the `_test_prequential_bagging.py` demo. One of the main issues is the lack of error message (in #21) and thus, if indeed related, there should be some explicit feedback if something goes wrong or unexpected.

**Comment by Darkmyter** [comment]
``predict_proba`` from ``Hoeffding_tree`` seems to be working fine and its output is as follows: ```[[0.2, 0.3, 0.5], [0.4, 0.6, 0.0]]``` for 2 samples and 3 classes, and with these results ``predict`` provides the same predictions as without ``predict_proba``.
the ``normalize_values_in_dict`` output may vary from 3.6 and 3.4, 3.5.
Exemple:
```
[0.4497009191972877, 0.37095206116508905, 0.009627766164113276, 0.16971925347350986]
[0.4497009191972878, 0.3709520611650891, 0.009627766164113278, 0.16971925347350988]
```
This difference is very small and would not affect the predicting results.

This classifier ```classifier = LeverageBagging(h=HoeffdingTree(), ensemble_length=2)``` is able to be partially fit and to give prediction results.
``_test_prequential_bagging.py`` was giving this error ``The first partial_fit call should pass all the target_values.`` which seemed to be caused by the renaming of the stream attribute ``target_values`` that was not done correctly.  
 After changing that when the classifier ``classifier`` is evaluated as in ``_test_prequential_bagging.py``, it gives this output:
```
root - INFO - Prequential Evaluation
root - INFO - Evaluating 1 target(s).
root - INFO - Pre-training on 2000 samples.
root - INFO - Evaluating...
root - INFO - 10.0%
root - INFO - Evaluation time: 1.977 s
root - INFO - Total samples: 2097
root - INFO - Global performance:
root - INFO - Model 0 - Accuracy     : 0.979
root - INFO - Model 0 - Kappa        : 0.945
root - INFO - Model 0 - Kappa T      : 0.952
'NoneType' object is not iterable
```

**Comment by jacobmontiel** [comment]
In traditional classification problems the classes are known in advance. Nonetheless, emerging classes represnrt are a real issue and we need to make sure to support this case. Considering this, we could use `max(votes.keys())` where `votes` is the dictionary containing the leaf statistics.
Comments @jmread?

**Comment by krifiMedAmine** [comment]
we are already using `max(votes.keys())` in the implementation of `predict_proba()`

`
