### ISSUE TITLE
[BUG] HalfSpaceTrees requires undocumented n_features parameter

### ISSUE THREAD

**Issue by JosephTLucas** [scikit-multiflow/scikit-multiflow#263]
**Describe the bug**
When working through this example https://scikit-multiflow.readthedocs.io/en/stable/api/generated/skmultiflow.anomaly_detection.HalfSpaceTrees.html#skmultiflow.anomaly_detection.HalfSpaceTrees (on W10, python 3.7.6, skmultiflow 0.4.1), I get a type error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-15-44f8f0d1319f> in <module>

----> 1 hs = HalfSpaceTrees(random_state=1)

TypeError: __init__() missing 1 required positional argument: 'n_features'
```

This goes away if I add that parameter.

**To Reproduce**
Steps to reproduce the behavior (minimal working example, if applicable).
```
# Imports
from skmultiflow.data import AnomalySineGenerator
from skmultiflow.anomaly_detection import HalfSpaceTrees
# Setup a data stream
stream = AnomalySineGenerator(random_state=1, n_samples=1000, n_anomalies=250)
# Setup Half-Space Trees estimator
half_space_trees = HalfSpaceTrees(random_state=1)
```

**Expected behavior**
Code should work as demonstrated in the documentation.  It does work if you add n_features to the initialization call.

**Comment by smastelini** [comment]
Hi @JosephTLucas, thanks for reporting. The `n_features` parameter has been deprecated since version 0.5.3. The available documentation, hosted at _readthedocs_, refers to the versions 0.5.*. I suggest you upgrading your skmultiflow version to the latest one (available in both pip and conda).

**Comment by JosephTLucas** [comment]
Oh I guess when I installed from conda  those morning, I thought it would be updated. Thanks!
