### ISSUE TITLE
A new StreamEvaluator that supports multiple Stream-StreamModels

### ISSUE THREAD

**Issue by wnich444** [scikit-multiflow/scikit-multiflow#27]
I created a very similar project internally at our organization before I became aware of your work, and we thought it'd be a good idea to work with the community instead of duplicating effort. 

The primary architectural difference is that there is a type of StreamEvaluator that is more like a pipeline (a FlowingPipeline, if you will), in that it supports a list of Stream-StreamModel pairs. Each Stream after the first one receives the transformed output of the previous StreamModel. 

Would you be open for the addition of this feature? If so, I can make a feature branch and create relevant changes and associated documentation for a more detailed review.

**Comment by jacobmontiel** [comment]
Hi @wnich444 , that sounds very interesting and would be a nice feature to add to `scikit-multiflow`. 

We have a prototype of pipelines were we are basically chaining "transform" operations. You can check it here:
https://github.com/scikit-multiflow/scikit-multiflow/blob/master/src/skmultiflow/core/pipeline.py

Let me know what you think.

**Comment by wnich444** [comment]
Yeah I did see that! I believe the ability to tie Streams with Transformers lets you do interesting stuff beyond what you can do with a series of Transformers. For example, passing just the latest sample to the first Transformer, but passing a rolling window of data to the second. 

I had a couple other features that align with this concept, but I'll propose those incrementally.

**Comment by jacobmontiel** [comment]
Going through the backlog. @wnich444 could you provide an update on the status of this issue?

**Comment by jacobmontiel** [comment]
Closing this issue as there are no updates/changes.
