### ISSUE TITLE
ConceptDriftStream generator

### ISSUE THREAD

**Issue by MelchiorChui** [scikit-multiflow/scikit-multiflow#28]
Request to add ConceptDriftStream generator as in MOA to scikit-multiflow.

Example:

```
WriteStreamToARFFFile -s (ConceptDriftStream -s generators.AgrawalGenerator -d (ConceptDriftStream -s (generators.AgrawalGenerator -f 2) -d (ConceptDriftStream -s generators.AgrawalGenerator -d (generators.AgrawalGenerator -f 4) -p 25000 -w 10000) -p 25000 -w 1) -p 25000 -w 10000) -f example4.arff -m 100000
```
Multiple concept drifts can be simulated with nesting, and each drift can have its position and width manually adjusted. In this case, three shifts at 25000, 50000, 75000 with widths 10000, 1, 10000, using AGRAWAL generators with different classification functions.

Plotting rolling mean yields a graph like:

![screen shot 2018-07-02 at 11 02 32 am](https://user-images.githubusercontent.com/40759448/42158132-84a8c1ee-7de7-11e8-915a-fd564ec2c14d.png)

**Comment by krifiMedAmine** [comment]
A 'ConceptDrfitStream' generator is now available 06f3de997d36effb1c0b29361612f00b2be7c54c
