### ISSUE TITLE
Error on Naive Bayes: Can't instantiate abstract class NaiveBayes with abstract methods reset

### ISSUE THREAD

**Issue by foxriver76** [scikit-multiflow/scikit-multiflow#29]
Hi,

when I try to use the NaiveBayes, I receive the following error:

> Can't instantiate abstract class NaiveBayes with abstract methods reset

The code looks like this:

```
from skmultiflow.data.generators.waveform_generator import WaveformGenerator
from skmultiflow.evaluation.evaluate_prequential import EvaluatePrequential
from skmultiflow.classification.naive_bayes import NaiveBayes

stream = WaveformGenerator()

stream.prepare_for_use() 

clf = NaiveBayes()

evaluator = EvaluatePrequential(show_plot=True, 
                                pretrain_size=500,
                                max_samples=50000,
                                metrics=['performance', 'kappa']) 

evaluator.evaluate(stream=stream, model=clf) 
```

It would be great, if you could explain me why this isn't working.

thank you.

**Comment by jacobmontiel** [comment]
Thanks for reporting this @foxriver76 

I confirmed the bug and the fix is in place. To test I used `SineGenerator` and `SEAGenerator` since the data from `WaveGenerator` raises an error due to negative X.
