### ISSUE TITLE
Hoeffding Tree stops too early with "Can not normalize, normalization factor is zero"

### ISSUE THREAD

**Issue by foxriver76** [scikit-multiflow/scikit-multiflow#30]
At first: Thanks for fixing the Naive Bayes issue that fast. ;)

When I use Hoeffding Tree it stops long before max_samples is reached with the following info in the log

> Can not normalize, normalization factor is zero

The used Code looks like this:

```
from skmultiflow.data.generators.waveform_generator import WaveformGenerator
from skmultiflow.data.generators.sea_generator import SEAGenerator
from skmultiflow.evaluation.evaluate_prequential import EvaluatePrequential
from skmultiflow.classification.trees.hoeffding_tree import HoeffdingTree

stream = WaveformGenerator()
#stream = SEAGenerator()

stream.prepare_for_use() 

clf = HoeffdingTree()

evaluator = EvaluatePrequential(show_plot=True, 
                                pretrain_size=250,
                                max_samples=50000,
                                metrics=['performance', 'kappa']) 

evaluator.evaluate(stream=stream, model=clf)

```

Result is:

> root - INFO - Prequential Evaluation
> root - INFO - Evaluating 1 target(s).
> root - INFO - Pre-training on 250 samples.
> root - INFO - Evaluating...
> root - INFO - 5.0%
> root - INFO - 10.0%
> root - INFO - 15.0%
> root - INFO - Evaluation time: 6.437 s
> root - INFO - Total samples: 8201
> root - INFO - Global performance:
> root - INFO - Model 0 - Accuracy     : 0.797
> root - INFO - Model 0 - Kappa        : 0.696
> Can not normalize, normalization factor is zero

Also when I use the other stream generator (SEAGenerator), it stops at about 3.4k samples.

**Comment by jacobmontiel** [comment]
Can't replicate. A known issue raised this error and has been addressed.

 @foxriver76 Can you confirm that you are using the latest version of the Hoffding Tree?

**Comment by foxriver76** [comment]
You are right, it works in the latest version. Thank you.

**Comment by jacobmontiel** [comment]
Excellent, thanks!

**Comment by foxriver76** [comment]
Before I spam another issue, I have one question: Should the 'true_vs_predicts' metric work? Because I receive 

>   File "~/anaconda3/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 2184, in pts_to_prestep
>     steps = np.zeros((1 + len(args), 2 * len(x) - 1))
> 
> ValueError: negative dimensions are not allowed

**Comment by jacobmontiel** [comment]
'true_vs_predicts' is working. Here is an example using Anaconda with Python3.6.5 and setting the evaluator as follows:

``` python
evaluator = EvaluatePrequential(show_plot=True,
                                pretrain_size=250,
                                max_samples=50000,
                                metrics=['performance', 'true_vs_predicts'])
```

![true_vs_predicted](https://user-images.githubusercontent.com/17923265/42295161-d3eccc30-7fe7-11e8-9838-ae447f08c6d7.png)

On the other hand, the error is raised by matplotlib. Did you get any hint on `scikit-multiflow`'s side?

**Comment by foxriver76** [comment]
Got it. Was an issue with matplotlib like you said.

**Comment by Giseem5** [comment]
Hi, I'm having this issue. I installed the latest version, but I still get "Can not normalize, normalization factor is NaN"

Thanks.

**Comment by jacobmontiel** [comment]
Hello @Giseem5 

Could you provide an MWE of the code that triggers this error?

**Comment by DiaaAj** [comment]
Hello @jacobmontiel
I'm trying to detect drifts using Hoefdding Tree and I get the same error. my dataset is tfidif vectors with 500 features (it contains zeros and values between 0-1). Here's a snippet of my code

```
def detect_drift_ddm(X, y, time_step = 100):
    
    detector = DDM()
    classifire = HoeffdingTree()
    total_drifts = 0
    
    stream = DataStream(X_train, y_train)
    stream.prepare_for_use()

    X_train, y_train = stream.next_sample(200)
    classifire.partial_fit(X_train, y_train, classes=np.unique(y_train))

    for i range(len(X_train)-200):
        X_train, y_train = stream.next_sample()
        y_pred = classifire.predict(X_train.reshape(1,-1))[0]
       
        detector.add_element(int(not accuracy_score(y_train.reshape(1, -1).ravel(), y_pred.reshape(1,-1))))   
        if detector.detected_change():
            classifire = HoeffdingTree()
            total_drifts += 1
            classifire.partial_fit(X_train[i].reshape(1,-1), y_train[i].reshape(1,-1).ravel(), classes = np.unique(y_train))
        else:
            classifire.partial_fit(X_train[i].reshape(1,-1), y_train[i].reshape(1,-1).ravel())
   
    return total_drifts
```
Sorry if this isn't the right place to ask this question. Thanks.
