### ISSUE TITLE
Stream of samples with delayed responses

### ISSUE THREAD

**Issue by sam31415** [scikit-multiflow/scikit-multiflow#35]
This is just a question. Suppose my samples are produced as a stream, but that I cannot know the response before a certain delay (during which new samples are produced and need to be predicted). In the simple examples in the doc, it looks like the model is evaluated right after it made its prediction. Is there a way to somehow delay the evaluation, allowing for other samples to be predicted in the mean time?

**Comment by jacobmontiel** [comment]
Hello, @sam31415 . Neither the Streams nor the Evaluators support delays. Given that the delay is coming from the Stream, the easiest solution I can think of is to create a DelayedStream class that takes a Stream object and adds the delay in the `next_sample()` method. The other methods can be just masks to the method in the base Stream.

**Comment by sam31415** [comment]
@jacobmontiel Thanks for the suggestion. Looking at the Stream class, I feel this won't help, because the delay concerns the evaluator as well. 

Maybe I didn't explain the problem very well, so let me be more concrete. Suppose you have the following toy machine learning problem. Sick patients are coming one after the other, you measure various features on each patient, and you want your ML algorithm to decide whether to give them medication A or medication B. The response is whether the patient healed (by some measure) after one week. So given a patient, you have to make a prediction now, but you can't train your algorithm on this sample until the next week. In the mean time, more patients are coming, for which the algorithm has to make predictions. Even when evaluating the model offline, where you already know all the responses, you cannot just predict and train the model sequentially, as this would introduce look ahead bias and overestimate the algorithm performance.

My question is whether scikit-multiflow could handle such "delayed training". 

I guess you probably would need to tag each sample both with a time at which the prediction has to be made, and a time where the response become available. Then maybe this could implemented by rewriting the evaluation class...

**Comment by jacobmontiel** [comment]
Hi @sam31415 , sorry for the delay. I agree with you, considering your example the best option would be to modify the evaluator to "hold" training until further notice. Then you could account for the 'efficiency' of the answer by "weighting" the sample when training. This is something that can be handled but the above-mentioned change is required.

Any comment @jmread ?

**Comment by jmread** [comment]
Good suggestion @sam31415 delayed training will be very useful. According to my familiarity with this problem, although training should be delayed -- depending on when true labels are made available -- testing should carry on ahead -- correct? At point `t` in time, the most recent label available for training may be `y[t-10]`, correct? @jacobmontiel This is not prequential, probably we will need an `evaluate_delayed.py` or something, what do you think?.

**Comment by jacobmontiel** [comment]
+1 for `evaluate_delayed.py`. I think the training would be more complex than just `y[t-10]` since different samples might be "ready" for training at different times, without constraints on the order of the first appearance.

**Comment by sam31415** [comment]
@jmread I'm not sure what you mean exactly by "testing should carry on ahead". As Jacob mentioned, in general we don't know how many samples will have to be predicted before we obtain the response for a given sample and are able to train the model on it. So a fixed lag, as you seem to suggest, would be too restrictive.

I think the most natural way of implementing such delayed learning would be to have both the features and the response to be time tagged (i.e. have two additional columns in the dataframe). In this way it is possible to know exactly when a sample should be used for prediction and for training. Having time tagged data is anyway very natural if you are doing online learning. In the absence of time-tagged data the estimator could simply predict and train sequentially by default.

**Comment by jmread** [comment]
I mean that testing should be done even if training examples are not ready yet. This fits in with our own example -- we still need to decide 'A' or 'B' for one instance whenever a decision is required (i.e., fixed time). It is the training which should be done in variable time. 
I believe the lag should be specified in the number of time steps, rather than continuous time, in the framework. 
Your suggestion is welcome.

**Comment by sam31415** [comment]
Sure this would work as well, but I feel it would be less convenient. Any data you may collect to train an online model will be timestamped. If you implement the logic in terms of lags, every user will have to convert their timestamps into lags. It may be more natural and convenient to work with timestamped data from the start.

**Comment by LauAvinyo** [comment]
Hello,
I am encountering a problem super similar to this toy example. :)
Finally, did someone implement this idea? If so, which is the class/method name? Otherwise, could I do it?
Best,

**Comment by jacobmontiel** [comment]
Hello @LauAvinyo, this functionality has not been implemented in `skmultiflow`. If you are interested in working on this it would be great.

@sam31415 are you ok with this? Any suggestion or comment is more than welcomed.

@LauAvinyo let us know if we can be of help.

**Comment by LauAvinyo** [comment]
@jacobmontiel Perfect! I will wait a couple of days to see if sam answers. :) If not I will start doing!
Thanks!

**Comment by sam31415** [comment]
Please feel free to implement this.

**Comment by jacobmontiel** [comment]
> Please feel free to implement this.

Thanks @sam31415!

**Comment by jacobmontiel** [comment]
Hello @LauAvinyo, just reaching out to confirm that I can assign you this issue.

Also taking the chance to ping @hmgomes who might find this interesting.

**Comment by LauAvinyo** [comment]
@jacobmontiel. Yes! I am on it... I am just slow... :)

**Comment by jacobmontiel** [comment]
No problem at all :-) 

I will remove the `help wanted` label

**Comment by hmgomes** [comment]
> Hello @LauAvinyo, just reaching out to confirm that I can assign you this issue.
> 
> Also taking the chance to ping @hmgomes who might find this interesting.

Yes, I find it very interesting @jacobmontiel :)
We've been discussing an appropriate design for that in MOA for a while now, the goal is to propose one by the end of this year.

**Comment by jacobmontiel** [comment]
Hi @LauAvinyo, we have found a person to take over this task. Could you confirm if you are ok with this?

**Comment by LauAvinyo** [comment]
@jacobmontiel that is a pity because I am about to finish! But yes, sure, I am ok with it!
Let's see if in about two months you have more tasks to do ;)
