### ISSUE TITLE
HoeffdingTree returns prediction as list 

### ISSUE THREAD

**Issue by lfleck** [scikit-multiflow/scikit-multiflow#39]
### Expected behaviour
All predictions are returned as Numpy arrays

### Actual behaviour
HoeffdingTree returns lists

https://github.com/scikit-multiflow/scikit-multiflow/blob/39a78801b38e0e3492199cc3a5bfb0ab09c58123/src/skmultiflow/trees/hoeffding_tree.py#L1045-L1048

https://github.com/scikit-multiflow/scikit-multiflow/blob/39a78801b38e0e3492199cc3a5bfb0ab09c58123/src/skmultiflow/trees/hoeffding_tree.py#L1067-L1070

Just a comment: 
The HoeffdingTree classifier runs extremly slow on my machine (about 8s for a batch of my data vs. < 1s for all sklearn classifiers that I tested, including MLP with 100 hidden nodes). Would it be possible to improve the runtime performance somehow?

**Comment by jacobmontiel** [comment]
Thanks for pointing this out @lfleck 

This behaviour is widespread in the project, given that for storing the predictions, using `lists` is faster.

For the common case where we are returning predictions for one sample:
```python
%%timeit
a= []
for i in range(1): a.append(i)

>>> 338 ns ± 1.11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

%%timeit
b = np.zeros(1)
for i in range(1): b[i] = i

>>> 1.01 µs ± 7.01 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
 
Same behaviour for storing 1M values:
```python
%%timeit
a= []
for i in range(1000000): a.append(i)

>>> 82.8 ms ± 238 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

b = np.zeros(1000000)

%%timeit
b = np.zeros(1000000)
for i in range(1000000): b[i] = i

>>> 130 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

On the other hand, `scikit-learn` uses np.arrays and maybe we have to compromise performance for interoperability. It is an interesting decision. What do you think @jmread ?

**Comment by jacobmontiel** [comment]
Regarding the performance of Hoeffding Trees, we are aware that it is not ideal. `scikit-learn` is a mature library and is highly optimized (Cython, C code, etc.). Also important is that in batch learning, we can benefit form libraries such as `numpy` which are optimized to work on large amounts of data, while stream data is basically small amounts of data processed at a time. This is by no means a justification and we definitely aim for better performance. We have tried some ideas, but so far have been unsuccessful. In our current development cycle, we focus on creating the core elements of `scikit-multiflow`. The next development cycle is likely to include optimizing the performance of specific elements. We welcome collaborations if somebody is interested in working on this challenge.

**Comment by jmread** [comment]
I can understand why most people might be wanting an array instead of a list. Sure, appending operations are faster - but many operations are much faster with arrays and that is why people like them. An easy fix is to simply cast the list to an array when returning it :-)
Probably Hoeffding Trees is an exception, there are many fewer matrix operations than, say MLPs. As @jacobmontiel points out, there is no doubt that a faster implementation of Hoeffding Trees is high on the TODO list, and we welcome any collaboration towards this.

**Comment by lfleck** [comment]
I can fully understand that performance is currently not at the top your lists, hence it was really just a comment. 
However, I would prefer `np.array` as return type. As a lot of streaming methods are learner independent frameworks, one might try them with different classifiers or regressors, including the ones from `scikit-learn`. Of course a cast after receiving the prediction is always possible, but one would always have to check for the necessity first.

**Comment by jacobmontiel** [comment]
I am committing a fix based on @jmread  suggestion, so HT (HAT and LCHT) will now return np.array as default. A new issue will be created to propagate this change.
