### ISSUE TITLE
"List assignment index out of range" error only for some of the classification methods

### ISSUE THREAD

**Issue by Bilgecelik** [scikit-multiflow/scikit-multiflow#42]
Hi,
For one of my datasets, I receive this error after random number of evaluations for Hoeffding Tree, ARF and the meta models. The other models seem to work. Any idea why that can be?

![ht error](https://user-images.githubusercontent.com/38037323/43779968-d33d45d0-9a59-11e8-8601-411319bda481.JPG)

Attached is a sample of the csv file. The file seems okay but i think this is again a problem with file stream. 

[vehicle_sensIT.zip](https://github.com/scikit-multiflow/scikit-multiflow/files/2266718/vehicle_sensIT.zip)

**Comment by jacobmontiel** [comment]
Hello @Bilgecelik , can you share the code you are using? I tried to replicate the issue and got an error from `FileStream`

**Comment by Bilgecelik** [comment]
Hi Jacob, yes sure! You need to specify target attribute as 0 for that dataset, maybe that's the error.

[Benchmark_runs.zip](https://github.com/scikit-multiflow/scikit-multiflow/files/2270050/Benchmark_runs.zip)

**Comment by jacobmontiel** [comment]
Thanks! Looking into the data set there are some values in the data set that are raising this issue:
- Empty values (NaN)
- '-'

I solved this by pre-processing the dataset with pandas and then using `DataStream` to convert the data into a Stream. Here is the code I used:

```python
data = pd.read_csv('/home/jacob/Documents/workspace/tmp/skmultiflow--issues/vehicle_sensIT.csv')
data.fillna('0', inplace=True)                    # Fill NAN
data.replace('-', 0, inplace=True)                # Replace invalid values
data.replace({'Y': -1}, 0, inplace=True)          # Set targets as {0, 1}
obj_cols = data.select_dtypes(include='O').columns.values.tolist()
data[obj_cols] = data[obj_cols].astype(float)     # Cast object (string) type columns to float
columns = data.columns.values.tolist()
columns.remove('Y')
columns.append('Y')
data = data.reindex(columns, axis=1)              # Move y to the end of the DataFrame (optional)
print(data.head())

stream = DataStream(data=data)
stream.prepare_for_use()
```

On the other hand, I still get an error (as expected) when loading the data set using `FileStream`. 

Let me know if this helps.

**Comment by Bilgecelik** [comment]
Hey Jacob,
This seems to solve it! My FileStream reads it and now all the methods work. For the unprepared dataset, I was still able to read it (hence didn't understand the problem) and it worked normal for some methods though, you may want to look into that. Thanks for your help!
