### ISSUE TITLE
Information about label frequency

### ISSUE THREAD

**Issue by foxriver76** [scikit-multiflow/scikit-multiflow#43]
Is there any possibility to get the label frequency at the end of an evaluation?

Otherwise it would be a great feature.

**Comment by foxriver76** [comment]
An example: 

I have a binary classification dataset with labels 0 and 1. I'm only evaluating a subset of the data. 

How can I get information about how often the label 0 was in the evaluated stream?

**Comment by jacobmontiel** [comment]
I see what you mean now. Unfortunately, the evaluator does not include such functionality. The only thing I can think of is that, if you are using as a source a static data set (file), you could loop the stream independently to calculate the label ratio.

You can define the number of samples to get `X, y = stream.next_sample(n_samples)`and then just evaluate the ratio in y. Not the most elegant solution but it may help.

**Comment by foxriver76** [comment]
Okay, thank you.

**Comment by foxriver76** [comment]
Shouldn't Kappa M statistics contain these informations somewhere in the background due to the fact that it compares to a majority vote classifier (which has to know the label frequency).

**Comment by jacobmontiel** [comment]
The Kappa M statistic is calculated using a confusion matrix that is updated continuously. Unfortunately, this data structure does not keep track of the arriving order, just the number of votes.
