### ISSUE TITLE
Documentation on ConceptDriftStream Generator

### ISSUE THREAD

**Issue by foxriver76** [scikit-multiflow/scikit-multiflow#44]
With https://github.com/scikit-multiflow/scikit-multiflow/commit/06f3de997d36effb1c0b29361612f00b2be7c54c a ConceptDriftStream generator was introduced. Unfortunately there is no documentation on it and I can't import the generator without modifications on scikit-multiflow

**Comment by jacobmontiel** [comment]
Thanks for reporting the missing documentation.

It is available at:
https://scikit-multiflow.github.io/scikit-multiflow/skmultiflow.data.concept_drift_stream.html#module-skmultiflow.data.concept_drift_stream

Could you elaborate on why you can't import the generator?

**Comment by foxriver76** [comment]
Thanks for adding the documentation -- very helpful.
Import also works -- I was just confused because my Spyder installation did not auto complete the desired package.
