### ISSUE TITLE
Issue with reading dataset as pd.DataFrame

### ISSUE THREAD

**Issue by Bilgecelik** [scikit-multiflow/scikit-multiflow#49]
Hi, I am trying to download datasets as pd.DataFrame and convert them to DataStream after, but the streams seem to be empty and prepare_to_use function is not working giving the error 'numpy.ndarray' object has no attribute 'columns'. Here is my code, in which I can see the data until DataStream function.

for i in range(6):
    dataset = oml.datasets.get_dataset(idy[i][0])
    X, y, attribute_names = dataset.get_data(
        target=dataset.default_target_attribute,
        return_attribute_names=True,)
    data = pd.DataFrame(X, columns=attribute_names)
    data['class'] = y
    stream = DataStream(data=data)
    list_of_streams.append(stream)

Bilge

**Comment by jacobmontiel** [comment]
Hi @Bilgecelik , are you running the data loading and stream generation inside the `for` loop?

Can you confirm that the stream object in `list_of_streams` are different?
```python
for stream in list_of_streams:
    print(id(stream))
```

What happens if you try `range(1)`?

**Comment by Bilgecelik** [comment]
Hi Jacob, yes i do those in for loop since i have multiple datasets. These are the ids:
![image](https://user-images.githubusercontent.com/38037323/44852788-7128b380-ac64-11e8-9d5f-af55e18684b7.png)
i tried range(1) and it worked. Now i changed to higher range again and they are all working. Not sure what happened there, but it is solved. Thanks for your help!
