### ISSUE TITLE
The memory contabilization might not take into account the objects pointed by the variables

### ISSUE THREAD

**Issue by smastelini** [scikit-multiflow/scikit-multiflow#56]
Greetings,

I think I found an issue in the memory costs calculation of the Hoeffding Tree-based algorithms.

The use of `sys.getsizeof` alone over an class object, list, dictionary, among others, does not account for the actual sizes of the properties contained within the structures, but only the pointers to them. For example:

```python
import sys

sys.getsizeof([]) # returns 64
sys.getsizeof(1) # returns 28

sys.getsizeof([1]) # returns 72
sys.getsizeof([1, 1]) # returns 80
```

This simple example shows that Python calculates the byte size only considering the pointers to the actual referenced objects. 

This kind of issue is discussed in https://code.tutsplus.com/tutorials/understand-how-much-memory-your-python-objects-use--cms-25609.

An elegant solution is presented in https://goshippo.com/blog/measure-real-size-any-python-object/.

Applications which need to measure the memory costs of a solution would benefit from such strategy.

**Comment by jacobmontiel** [comment]
Functionality is added in afdf7c7f209112bf7c931d01c174c97690fc023a
