### ISSUE TITLE
RegressionHoeffdingTree fails when number of samples is less than 20

### ISSUE THREAD

**Issue by dihiaboulegane** [scikit-multiflow/scikit-multiflow#58]
When evaluating on a stream of less than 20 samples, a 'Division by zero' Exception is raised

**Comment by jacobmontiel** [comment]
Possibly related to #59

**Comment by jacobmontiel** [comment]
Upon investigation, the exception is actually raised by the `EvaluatePrequential` class. Given that a stream with less than 20 samples is not normal we won't add a special case to handle it. 

A proper error message will be added to request a stream with at least 20 samples.
