### ISSUE TITLE
Should `predict_proba` be implemented for AdaptiveRandomForest?

### ISSUE THREAD

**Issue by PGijsbers** [scikit-multiflow/scikit-multiflow#62]
I would like to use a AdaptiveRandomForest model and predict class probabilities with it.
To this end, I made a `predict_proba` implementation for it. Is this something that is desired to be added to the main repository?
If so, I will add documentation/tests and create a PR.

**Comment by jacobmontiel** [comment]
@PGijsbers 

Absolutely! We welcome all improvements on the framework.

**Comment by PGijsbers** [comment]
(For others) I'm working on this.

**Comment by PGijsbers** [comment]
As mentioned in #64, the individual estimator may return 'class probabilities' of 0, indicating not enough information. How should the Adaptive Random Forest handle this? I see three options:
 1. if *any* estimator gives  'probabilities' of 0, the ARF will also do this.
 2a.  if *any* (but not all) estimators do this, you average all 'probabilities' and don't normalize them to sum to 1.
 2b.  if *any* (but not all) estimators do this, you average all 'probabilities' and then normalize them to sum to 1.

In all cases, should all estimators give 'probabilities' of 0, ARF should also return 'probabilities' of 0.

Am I missing something? Is it clear? What do you think is the desired behaviour?

**Comment by jacobmontiel** [comment]
Getting the author of Adaptive Random Forest into the loop.

Hey @hmgomes , comments?

**Comment by hmgomes** [comment]
Hi @jacobmontiel and @PGijsbers 

This is an interesting and important discussion. Given these options I would go with option 2, specifically 2b. The intuition is: let the learners that are producing outputs govern the ensemble output.   

Cheers, 
Heitor

**Comment by PGijsbers** [comment]
Thank you for your input!
I personally like 2b the best as well. If @jacobmontiel is satisfied with that behavior I'll go ahead and finalize my work as such.
