### ISSUE TITLE
ARFBaseLearner incorrectly passes weights as classes (for HoeffdingTrees)

### ISSUE THREAD

**Issue by PGijsbers** [scikit-multiflow/scikit-multiflow#63]
The `ARFBaseLearner`'s `partial_fit` calls its classifier's `partial_fit` using only positional arguments [here](https://github.com/scikit-multiflow/scikit-multiflow/blob/master/src/skmultiflow/meta/adaptive_random_forests.py#L429-L432):

```  
def partial_fit(self, X, y, weight, instances_seen):
    self.classifier.partial_fit(X, y, weight)

    if self.background_learner:
        self.background_learner.classifier.partial_fit(X, y, weight)
    ...
```
Weight is passed as third positional, however, for the default classifier which derives from `HoeffdingTree` this is wrong. The signature of [`HoeffdingTree.partial_fit`](https://github.com/scikit-multiflow/scikit-multiflow/blob/master/src/skmultiflow/trees/hoeffding_tree.py#L949):

`def partial_fit(self, X, y, classes=None, weight=None):`

The weight value passed is thus interpreted as `classes` and `weight` is None ([which then defaults to 1.0](https://github.com/scikit-multiflow/scikit-multiflow/blob/master/src/skmultiflow/trees/hoeffding_tree.py#L983-L984)).

If you are interested, I fixed this by using keyword arguments, while working on `predict_proba` mentioned in #62.
I only tested with the default ARFHoeffdingTree, but should every `partial_fit` function (that's a suitable `ARFBaseLearner`) take keyword arguments `weight` and `classes`? Because then it should generalize too.

**Comment by PGijsbers** [comment]
Okay, so I noticed predictions change for the worse when making the change (0.653->0.469).
I'll go over it again to make sure I did not make any mistakes.
If everything is correct, I don't know that there is anything to do about it, but it makes sense to have a second set of eyes look at the changes?

**Comment by jacobmontiel** [comment]
I will take a look into this. Just to confirm, the bug was affecting the weight assigned to the sample (posisson), which in the current version defaulted to 1.

**Comment by PGijsbers** [comment]
Yes, from my understanding weights were -always- set to 1 because the passed weight was interpreted as `classes`. With the change, the Poisson RV is now the assigned weight instead.
