### ISSUE TITLE
ARF not working on multi-class classification using LED, AGrawal, and Waveform

### ISSUE THREAD

**Issue by jche117** [scikit-multiflow/scikit-multiflow#65]
### Expected behaviour
Adaptive random forest to work on multi-class classification
### Actual behaviour
Error during evaluate pre-quential 
### Steps to reproduce the behaviour

tree_size = [2,5,10,20,30,40,50]
rootFile = "/home/ubuntu/Documents/scikit-multiflow-master/Experiments/"
b = 500
    

stream = LEDGenerator()

stream.prepare_for_use()
    
for j in tree_size:
        #for b in batch_size:
    rf = AdaptiveRandomForest(n_estimators= j)
    filename = "LED_24features_" + str(j)+ "trees_"+ str(b) + "batch"
    print(filename)

    evaluator = EvaluatePrequential(show_plot = False, pretrain_size=b, max_samples = (j+50)*100 )
    evaluator.evaluate(stream = stream, model = rf)

*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by jacobmontiel** [comment]
Confirmed. This is likely related to #63 which is being addressed. Will test once #63 in fixed.

**Comment by jacobmontiel** [comment]
Fixed in #63 and #66
