### ISSUE TITLE
Docstrings swapped by mistake

### ISSUE THREAD

**Issue by Sun-Yuting** [scikit-multiflow/scikit-multiflow#69]
### Expected behaviour
The docstrings of these two functions: `has_more_samples` and `n_remaining_samples` are swapped in both **file_stream.py** and **data_stream.py**. (Maybe in other files as well.)

### Steps to reproduce the behaviour

---
[*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by jacobmontiel** [comment]
I have updated the documentation. 

Thanks, @Sun-Yuting for reporting this.
