### ISSUE TITLE
model size and running time metrics display only three models

### ISSUE THREAD

**Issue by Darkmyter** [scikit-multiflow/scikit-multiflow#70]
When using the model size and running time metrics with more than 3 models only the first three are displayed.
![ht](https://user-images.githubusercontent.com/20753626/47417254-e18d1600-d777-11e8-869f-dd73b0f75e54.png)

---
[*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by Darkmyter** [comment]
With pycharm the pop window only zooms in when i try to make it bigger.
Can't the default size of the window depend on the items to display ?

**Comment by jacobmontiel** [comment]
Changing the size of the figure (window) could be an issue for people using notebook given that plot sizes are limited by the notebook cell size.

Note: If you are using PyCharm's SciView it is rather limited and can be disabled, uncheck: Settings | Tools | Python Scientific | Show Plots in Toolwindow.
