### ISSUE TITLE
Documentation for DDM unclear

### ISSUE THREAD

**Issue by lfleck** [scikit-multiflow/scikit-multiflow#81]
### Actual behaviour
The documentation for DDM says for the encoding of the binary input stream: 
https://github.com/scikit-multiflow/scikit-multiflow/blob/f64c1035e16cab9e3d21168824091eb05ae0447e/src/skmultiflow/drift_detection/ddm.py#L93 
However, that's a little bit confusing for me. The probability that gets computed by the method represents the error rate and the paper by Gama says "The Binomial distribution gives the general form of the probability for the random variable that represents the number of errors in a sample of n examples". Shouldn't then be the misclassifications encoded with 1 and the correct classifications encoded with 0?

---
[*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by jacobmontiel** [comment]
The error rate shouldn't change given that DDM only monitors 0's and 1's. Optionally, you can change the encoding when passing to DDM:

```python
dd,add_element(not y_true == y_pred)
```

**Comment by lfleck** [comment]
> Optionally, you can change the encoding when passing to DDM:
> 
> dd,add_element(not y_true == y_pred)

That's the encoding I expected. 

Given the update rule for the misclassification probability: 
https://github.com/scikit-multiflow/scikit-multiflow/blob/f64c1035e16cab9e3d21168824091eb05ae0447e/src/skmultiflow/drift_detection/ddm.py#L107

with the inital values `self.miss_prob = 1` and `self.sample_count = 1`, a correct classified sample encoded according to the documentation (label 1) would keep  `self.miss_prob = 1`, whereas a wrong classification encoded according to the documentaion (label 0) would reduce the rate to `self.miss_prob = 0`

**Comment by jacobmontiel** [comment]
I see what you mean, also ran some tests to confirm. I will update the documentation to:
```
1 indicates an error (miss-classification).
```

This will affects ```EDDM```.

Thanks @lfleck for reporting this.
