### ISSUE TITLE
Inconsistent metrics ['accuracy', 'kappa'] for multi_output stream.

### ISSUE THREAD

**Issue by HeartBeautifulSoup** [scikit-multiflow/scikit-multiflow#82]
Hello, I am a beginner of scikit-multiflow. A ValueError occurred when I ran the example using generated multi-label data: Inconsistent metrics ['accuracy', 'kappa'] for multi_output stream.
I would be grateful if you have any suggestions.

from skmultiflow.data.multilabel_generator import MultilabelGenerator
 # Setting up the stream
stream = MultilabelGenerator(n_samples=100, n_features=10, n_targets=8, n_labels=8, random_state=0)
stream.prepare_for_use()

# 2. Instantiate the HoeffdingTree classifier
ht = HoeffdingTree

# 3. Setup the evaluator
evaluator = EvaluatePrequential(show_plot=True,
                                 pretrain_size=200,
                                 max_samples=20000)

# 4. Run evaluation
evaluator.evaluate(stream=stream, model=ht)

Error message
"E:\Program Files\python\python.exe" "E:/Program Files/multi-Label/ele.py"
E:\Program Files\python\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "E:/Program Files/multi-Label/ele.py", line 43, in <module>
    evaluator.evaluate(stream=stream, model=ht)
  File "E:\Program Files\python\lib\site-packages\scikit_multiflow-0.1.0-py3.7-win-amd64.egg\skmultiflow\evaluation\evaluate_prequential.py", line 220, in evaluate
    if self._check_configuration():
  File "E:\Program Files\python\lib\site-packages\scikit_multiflow-0.1.0-py3.7-win-amd64.egg\skmultiflow\evaluation\base_evaluator.py", line 236, in _check_configuration
    raise ValueError("Inconsistent metrics {} for {} stream.".format(self.metrics, self._output_type))
ValueError: Inconsistent metrics ['accuracy', 'kappa'] for multi_output stream.

Process finished with exit code 1

**Comment by jmread** [comment]
Actually there isn't really an 'accuracy' metric for multi-output. You can score per label (Hamming score) or score per instance where all labels must match exactly (Exact match). These can be seen as too lenient and too harsh, respectively, hence Jaccard Index gives a nice 'in between' metric to use for multi-label data. In the multi-label literature this is sometimes referred to as 'accuracy'.

**Comment by jacobmontiel** [comment]
Also, notice that `HoeffdingTree` does not support multi-label data. You have to use another type of classifier such as "Label Combination Hoeffding Tree", "Multi-output learner", etc.

**Comment by HeartBeautifulSoup** [comment]
> Actually there isn't really an 'accuracy' metric for multi-output. You can score per label (Hamming score) or score per instance where all labels must match exactly (Exact match). These can be seen as too lenient and too harsh, respectively, hence Jaccard Index gives a nice 'in between' metric to use for multi-label data. In the multi-label literature this is sometimes referred to as 'accuracy'.

I have solved this problem in succession, thank you very much for your help.

**Comment by HeartBeautifulSoup** [comment]
> Also, notice that `HoeffdingTree` does not support multi-label data. You have to use another type of classifier such as "Label Combination Hoeffding Tree", "Multi-output learner", etc.

Thank you for your reminder.

**Comment by HeartBeautifulSoup** [comment]
> > Actually there isn't really an 'accuracy' metric for multi-output. You can score per label (Hamming score) or score per instance where all labels must match exactly (Exact match). These can be seen as too lenient and too harsh, respectively, hence Jaccard Index gives a nice 'in between' metric to use for multi-label data. In the multi-label literature this is sometimes referred to as 'accuracy'.
> 
> I have solved this problem in succession, thank you very much for your help.

If you are not bothered, I want to ask another question:
I change the other classifier ，just like you said "Label Combination Hoeffding Tree".but I have another problem.

%matplotlib notebook
from skmultiflow.data.multilabel_generator import MultilabelGenerator
from skmultiflow.trees.lc_hoeffding_tree import LCHT
from skmultiflow.evaluation.evaluate_prequential import EvaluatePrequential

# 1. Create a stream
stream = MultilabelGenerator(n_samples=100, n_features=10, n_targets=8, n_labels=8, random_state=0)
stream.prepare_for_use()
stream.prepare_for_use()

# 2. Instantiate the HoeffdingTree classifier
lcht = LCHT(n_labels=8)

# 3. Setup the evaluator
evaluator = EvaluatePrequential(show_plot=True,
                                pretrain_size=200,
                                max_samples=20000,
                                metrics = ['exact_match']
                               )

# 4. Run evaluation
evaluator.evaluate(stream=stream, model=lcht)

Error message:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-1f5ace911cef> in <module>()
     20 
     21 # 4. Run evaluation
---> 22 evaluator.evaluate(stream=stream, model=lcht)

f:\program files\python\lib\site-packages\scikit_multiflow-0.1.0-py3.6-win-amd64.egg\skmultiflow\evaluation\evaluate_prequential.py in evaluate(self, stream, model, model_names)
    225             self._init_file()
    226 
--> 227             self.model = self._train_and_test()
    228 
    229             if self.show_plot:

f:\program files\python\lib\site-packages\scikit_multiflow-0.1.0-py3.6-win-amd64.egg\skmultiflow\evaluation\evaluate_prequential.py in _train_and_test(self)
    346                 break
    347 
--> 348         self.evaluation_summary()
    349 
    350         if self.restart_stream:

f:\program files\python\lib\site-packages\scikit_multiflow-0.1.0-py3.6-win-amd64.egg\skmultiflow\evaluation\base_evaluator.py in evaluation_summary(self)
    609                 print('{} - Exact matches: {:.4f}'.format(
    610                     self.model_names[i],
--> 611                     self._data_buffer.get_data(metric_id=constants.EXACT_MATCH, data_id=constants.MEAN)[i]))
    612             if constants.J_INDEX in self.metrics:
    613                 print('{} - Jaccard index: {:.4f}'.format(

TypeError: 'NoneType' object is not subscriptable

**Comment by jacobmontiel** [comment]
Hello @HeartBeautifulSoup 

There was a bug triggered when using LCHT and the evaluator. I committed a fix 19cd95e54fb7edf3e3117f332b4eab157d6775e2

**Comment by HeartBeautifulSoup** [comment]
> Hello @HeartBeautifulSoup
> 
> There was a bug triggered when using LCHT and the evaluator. I committed a fix [19cd95e](https://github.com/scikit-multiflow/scikit-multiflow/commit/19cd95e54fb7edf3e3117f332b4eab157d6775e2)

@jacobmontiel 
Thank you very much for your help.
