### ISSUE TITLE
EvaluateHoldout() function Failed

### ISSUE THREAD

**Issue by yzhang017** [scikit-multiflow/scikit-multiflow#85]
### Expected behaviour
Should pass the following code:

train_arf = FileStream("covtype.csv")
train_arf.prepare_for_use()
ARF = AdaptiveRandomForest()
evaluator = EvaluateHoldout (max_time=1000, n_wait=1, batch_size = 10, metrics=['accuracy', 'true_vs_predicted'], dynamic_test_set=True)

evaluator.evaluate(stream=train_arf, model=ARF,model_names=['ARF'])

### Actual behaviour
Error:  'NoneType' object is not subscriptable

### Steps to reproduce the behaviour
I used the covtype.csv data from the data file.

---
[*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by garawalid** [comment]
If you reduce the `max_samples` in EvaluateHoldout, it will work correctly.
```
evaluator = EvaluateHoldout (max_time=1000,max_samples=1000, n_wait=1, batch_size = 10, metrics=['accuracy', 'true_vs_predicted'], dynamic_test_set=True)
```
Did the evaluating bar reaches 100% when you have this error ?
```
Evaluating...
 #################### [99%]
```

**Comment by yzhang17usf** [comment]
Yes, it is. The error shows after the evaluation bar reaches 100%.

**Comment by yzhang17usf** [comment]
Yes, you are correct. I change the max_time to max_samples, and it works
fine.

**Comment by garawalid** [comment]
Good! Also, I get this error when I leave it running. 
```
Time limit reached (1000.00s). Evaluation stopped.
```

**Comment by jacobmontiel** [comment]
Thanks for the info @yzhang17usf and @garawalid, it helped me out to figure this out quickly.

Two things:

1. The test configuration is a little unexpected given that you are setting the train set (`n_wait`) equal to one, while the default `test_size` is 5000.
2. The error was triggered for this unexpected configuration. I have committed a fix (6fd86e40dfbacd9ac9c5eb0ba6590f33450772cb) to address this scenario. Let me know if this works.

Now, two comments:

1. When using holdout evaluation you have control over the number of train and test samples. The usual setup is having a smaller test set, the default values are `n_wait=10000` and `test_size=5000`.
2. The holdout class does not support the option to save all test results into a file (even if you set `n_wait = 1`)

**Comment by yzhang17usf** [comment]
Thank you for explaining these. Does there have Concept Drift Hoeffding
Tree?

Best,
Yan

**Comment by jacobmontiel** [comment]
What do you mean by Concept Drift Hoeffding Tree? The closest method I can think of is the *Hoeffding Adaptive Tree* which is available in the package.

**Comment by yzhang17usf** [comment]
Sorry, it is called Concept-adapting Very Fast Decision Tree learner.

**Comment by jacobmontiel** [comment]
I see, `scikit-multiflow` does not have an implementation of `CVFDT`, hoewever the `Hoeffding Adaptive Tree` is a drift aware metod that has been shown to have better performance than `CVFDT`:

http://www.lsi.upc.edu/~abifet/Adwin-DT.pdf

**Comment by yzhang17usf** [comment]
Thank you so much.

Best,
Yan
