### ISSUE TITLE
Hoeffding Tree leaves' distribution varies depending on the python version

### ISSUE THREAD

**Issue by garawalid** [scikit-multiflow/scikit-multiflow#91]
### Expected behaviour
For the same code, the final results of `Hoeffding Tree` should be the same regardless of the version of python.
### Actual behaviour

`Hoeffding Tree` returns a different probability for the same code, and this probability is the same in python 3.4 & 3.5 but different in 3.6. This behaviour doesn't depend on `leaf_prediction`. 

Also, the classifier has the same model (tree) in the end for each version of python. 

I did a little digging, and I found that the origin of the problem is in the final values of `_observed_class_distribution` of active nodes.

Here is a quick example: 

```python
    stream = RandomTreeGenerator(tree_random_state=23, sample_random_state=12, n_classes=2, n_cat_features=2,
                                     n_categories_per_cat_feature=4, n_num_features=1, max_tree_depth=30,
                                     min_leaf_depth=10,
                                     fraction_leaves_per_level=0.45)
    stream.prepare_for_use()

    learner = HoeffdingTree(nominal_attributes=[i for i in range(1, 9)], leaf_prediction='nba')

    cnt = 0
    max_samples = 15000
    predictions = array('i')
    proba_predictions = []
    wait_samples = 100

    while cnt < max_samples:
        X, y = stream.next_sample()
        # Test every n samples
        if (cnt % wait_samples == 0) and (cnt != 0):
            predictions.append(learner.predict(X)[0])
            proba_predictions.append(learner.predict_proba(X)[0])
        learner.partial_fit(X, y)
        cnt += 1

    l_nodes = learner._find_learning_nodes()
    for node in l_nodes:
        print(node.node._observed_class_distribution.values())
        
```
```
# python3.6

dict_values([592.0, 535.0])
dict_values([227.0, 304.0])
dict_values([830.0, 542.0])
dict_values([1594.0, 1623.0])
dict_values([324.79304610816257, 582.6026022538947])
dict_values([822.2069538918374, 1131.3973977461053])
```
```
# python3.4 & 3.5
dict_values([587.0, 640.0])
dict_values([327.0, 254.0])
dict_values([830.0, 542.0])
dict_values([1414.0, 1529.0])
dict_values([582.6026022538947, 324.79304610816257])
dict_values([1131.3973977461053, 822.2069538918374])
```

---
[*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by jacobmontiel** [comment]
Likely related to #68

**Comment by garawalid** [comment]
@jacobmontiel Thanks for referencing the related issue. 
This behavior doesn't depend on `leaf_prediction`. The issue stills the same for `nba`, `nb` and `mc`. 
I'm investigating the issue, once I find the root of the problem, I will let you know.

**Comment by jacobmontiel** [comment]
I also noticed that the difference is in the distribution of nodes tracking nominal features. Although in #68 we are not using nominal features.

You can also use the following method to get the tree structure:

```
print(learner.get_model_description())
```


In Python 3.6
```
if Attribute 1 = 0:
  if Attribute 2 = 0:
    if Attribute 6 = 0:
      if Attribute 8 = 0:
        Leaf = Class 1 | {1: 592.0, 0: 535.0}
      if Attribute 8 = 1:
        Leaf = Class 0 | {1: 227.0, 0: 304.0}
    if Attribute 6 = 1:
      Leaf = Class 0 | {0: 830.0, 1: 542.0}
  if Attribute 2 = 1:
    Leaf = Class 1 | {0: 1594.0, 1: 1623.0}
if Attribute 1 = 1:
  if Attribute 0 <= 0.3640020565606644:
    Leaf = Class 0 | {1: 324.79304610816257, 0: 582.6026022538947}
  if Attribute 0 > 0.3640020565606644:
    Leaf = Class 0 | {1: 822.2069538918374, 0: 1131.3973977461053}
```

In Python 3.5:

```
if Attribute 1 = 0:
  if Attribute 2 = 0:
    if Attribute 6 = 0:
      if Attribute 8 = 0:
        Leaf = Class 1 | {0: 587.0, 1: 640.0}
      if Attribute 8 = 1:
        Leaf = Class 0 | {0: 327.0, 1: 254.0}
    if Attribute 6 = 1:
      Leaf = Class 0 | {0: 830.0, 1: 542.0}
  if Attribute 2 = 1:
    Leaf = Class 1 | {0: 1414.0, 1: 1529.0}
if Attribute 1 = 1:
  if Attribute 0 <= 0.3640020565606644:
    Leaf = Class 0 | {0: 582.6026022538947, 1: 324.79304610816257}
  if Attribute 0 > 0.3640020565606644:
    Leaf = Class 0 | {0: 1131.3973977461053, 1: 822.2069538918374}
```

**Comment by garawalid** [comment]
@jacobmontiel 
Do you know any other test that works in python3.5 and not in python 3.6? It can be useful. 
Thanks.

**Comment by jacobmontiel** [comment]
The only one I know is the test for ARF mentioned in #68 

/tests/meta/test_adaptive_random_forest.py

**Comment by garawalid** [comment]
@jacobmontiel 
It turns out that the problem is related to python 3.6+. In fact, the behavior of the dictionary changed.
```python
item = {}
item[1]='a'
item[0]='b'

print(item)
``` 
```
# python 3.6
 {1: 'a', 0: 'b'}
```
```
# python 3.5
 {0: 'b', 1: 'a'}
```
The method `items()` will pick elements from left to right. I noticed that we use this method a lot in `hoeffding_tree.py`, `nominal_attribute_class_observer.py` and more. Also, when we use python 3.6+, `_observed_class_distribution` can have different form of distribution like `{1: 1664.0, 0: 1713.0}` instead of `{0: 1664.0, 1: 1713.0}`. So, this will lead to wrong results of weights for each leaves. 

If you check your example, you will notice that the first leaf doesn't have the same weight, also, the class are not in the same order. 

I tracked all the operations that can lead to this disorder, and to solve it, I forced the `dict` to be in order that depends on key (class). 

Now, we have exactly the same results for all the version of python, even in terms of probabilities.

**Comment by jacobmontiel** [comment]
That is a nice finding @garawalid 

As you mention this is a major concern given the extense usage of dictionaries within `scikit-multiflow`

In this case, rather than protecting every step where dictionaries are used, we need to make sure that the dictionaries *keep the order* when new keys are added. Looking into the changes to the class observers I noticed this:

https://github.com/garawalid/scikit-multiflow/blob/c9b16c93b17b4cf07ed2daeb793ce3bfcb173b81/src/skmultiflow/trees/nominal_attribute_class_observer.py#L34-L36

```python
            for class_val, class_dist in self._att_val_dist_per_class.items():
                if list(class_dist.keys())[0] != 0 and len(class_dist.keys()) > 1:
                    self._att_val_dist_per_class[class_val] = dict(sorted(class_dist.items()))
```

The problem is that we are sorting the distributions dictionary on each call of `observe_attribute_class()`. This only needs to be done when adding a new key:value pair, which is done here:

https://github.com/garawalid/scikit-multiflow/blob/c9b16c93b17b4cf07ed2daeb793ce3bfcb173b81/src/skmultiflow/trees/nominal_attribute_class_observer.py#L24-L27

```python
            val_dist = self._att_val_dist_per_class.get(class_val, None)
            if val_dist is None:
                val_dist = {att_val: 0.0}
                self._att_val_dist_per_class[class_val] = val_dist
```

Let me know what do you thinks.

**Comment by garawalid** [comment]
@jacobmontiel 
I tried to check if they are sorted on each call of `observe_attribute_class()` then do the sorting. I agree with you, it's better to be done when adding a new key:value pair. 

What you suggest is not enough, there is a missing case when a new `att_val` comes, the result will be like this :   
```
1 <skmultiflow.trees.nominal_attribute_class_observer.NominalAttributeClassObserver object at 0x7fd369c0bcf8> :
	_att_val_dist_per_class : <class 'dict'>: {1: {0.0: 234.0}, 0: {0.0: 205.0}}
```

I solved it this way :

https://github.com/garawalid/scikit-multiflow/blob/7eff79deedbf2e40d805b3ab5d3ac0c6d8ca334f/src/skmultiflow/trees/nominal_attribute_class_observer.py#L25-L31
```python 
            if val_dist is None:
                val_dist = {att_val: 0.0}
                self._att_val_dist_per_class[class_val] = val_dist
                self._att_val_dist_per_class[class_val] = dict(sorted(self._att_val_dist_per_class[class_val].items()))
            if att_val not in val_dist:
                val_dist[att_val] = 0.0
                self._att_val_dist_per_class[class_val] = dict(sorted(self._att_val_dist_per_class[class_val].items()))
```

**Comment by jacobmontiel** [comment]
Looks good to me. By the way, the same consideration must be taken in the `NumericAttributeClassObserverGaussian`

**Comment by garawalid** [comment]
@jacobmontiel Thanks for reminding me.

**Comment by smastelini** [comment]
Hello everyone!

I have been following your discussions about the different dictionaries behaviours depending on the python version. Did you consider using  [`OrderedDict`](https://docs.python.org/2/library/collections.html#collections.OrderedDict) from the Python's built-in `collections` package?

**Comment by garawalid** [comment]
@smastelini Good question!

>  An OrderedDict is a dict that remembers the order that keys were first inserted.

It doesn't solve our problem. In fact, we want to have `_observed_class_distribution` and `_att_val_dist_per_class` with  ordered keys (ascending order). ei : `{0: {0.0: 234.0}, 1: {0.0: 205.0}}`
So if we use `OrderedDict` and `observe_attribute_class()` receives an instance X with label `1` then the second one with label `0`. We will not have the desired result. 

@jacobmontiel 
I noticed a strange behaviour in `dict` on python 3.5 that we have to pay attention to.
It turns out that if we give keys as a continue sequence of integer, and we add elements to the `dict` in any order. The final `dict` will be ordered by key 

```python
item = {}
item[3]='d'
item[0]='a'
item[1]='b'
item[2]='c'

print(item) 
# {0: 'a', 1: 'b', 2: 'c', 3: 'd'}
```
```python
item = {}
item[3]='d'
item[0]='a'
item[10]='b'
item[2]='c'
print(item) 
# {0: 'a', 10: 'b', 3: 'd', 2: 'c'}
```

**Comment by jacobmontiel** [comment]
The main takeaway from this issue is that we need to ensure that dictionary keys are kept sorted.
