### ISSUE TITLE
Bug in Page-Hinkley Test

### ISSUE THREAD

**Issue by gmartinon** [scikit-multiflow/scikit-multiflow#92]
### Expected behaviour

Page-Hinkley test is supposed to compute a running mean e.g.

x = [0, 1, 2]
x_mean = [0.0 , 0.5, 1.0 ]

### Actual behaviour

Retrieving the x_mean attribute of PageHinkley() with the same x, I get 

x_mean = [0.0, 2.0, 2.0]

Furthermore, adding a dozen of elements result in overflow. I think there is a problem in the implementation of this class.

### Steps to reproduce the behaviour
```
import numpy as np
from skmultiflow.drift_detection import PageHinkley
from skmultiflow.data.data_stream import DataStream
import matplotlib.pyplot as plt

data = np.arange(100)
stream = DataStream(data, n_targets=0)
stream.prepare_for_use()
ph = PageHinkley()
x_mean = []
while stream.has_more_samples():
    x, _ = stream.next_sample()
    x = np.asscalar(x)
    ph.add_element(x)
    x_mean.append(ph.x_mean)
plt.plot(x_mean);
```
---
[*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by gmartinon** [comment]
Actually, after a quick look at the source code, it seems that there are missing parentheses :

```
self.x_mean = self.x_mean + (x - self.x_mean) / 1.0 * self.sample_count
```

should be 

```
self.x_mean = self.x_mean + (x - self.x_mean) / (1.0 * self.sample_count)
```

**Comment by jacobmontiel** [comment]
Hello @gmartinon, I agree, the solution seems trivial. I am away from my computer so I will submit the fix by tomorrow. Thanks for reporting the issue and the fix.
