### ISSUE TITLE
LearnNSE implementation does not work on classifiers without partial_fit

### ISSUE THREAD

**Issue by bgulowaty** [scikit-multiflow/scikit-multiflow#93]
LearnNSE implementation does not work on classifiers without partial_fit.

It is caused by possible bug in the code, since `.fit(...)` method on classifier will never be executed when using classifiers from current version of scikit-learn api. 

https://github.com/scikit-multiflow/scikit-multiflow/blob/ddf104437132f3b75f3fa6d30195e09d7bcb3231/src/skmultiflow/meta/learn_nse.py#L69-L73

`estimator.fit(X, y, classes=classes) ` will always raise *TypeError* because _classes_ property is not known (it is in `.partial_fit`)

**Comment by jacobmontiel** [comment]
Good catch @bgulowaty
