### ISSUE TITLE
Page-Hinkley test implementation

### ISSUE THREAD

**Issue by gmartinon** [scikit-multiflow/scikit-multiflow#98]
### Expected behaviour

As I understand it, the Page-Hinkley test consists in monitoring a cumulative sum of a variable, corrected by its cumulative mean and eventually a non-zero delta parameter. 

On the one hand, in Gama et al 2014 (survey on concept drift, page 15), this cumulative sum is monitored against its minimum, to detect anomalous increases of the variable. 

On the other hand, following the CUSUM philosophy  the cumulative sum is always restricted to its positive part, which is equivalent to enforcing its minimum to zero.

### Actual behaviour

Looking at the source code, the implemented formula is :

`self.sum = self.alpha * self.sum + (x - self.x_mean - self.delta)`

and does not seem to monitor the cumulative sum against a minimum or an enforced minimum of zero.

I suppose the following update formula is more compliant to the original Page-Hinkley test :

`self.sum = max(0, self.alpha * self.sum + (x - self.x_mean - self.delta))`

---
[*Note:* For comments and usage-related questions please consider the [users group](https://groups.google.com/forum/#!forum/scikit-multiflow-users).

**Comment by jacobmontiel** [comment]
Upon investigation, it seems that this is indeed a bug in the calculation of the sum value and the suggested fix is correct.

Thanks for reporting this @gmartinon
